-- Test-only H2 schema. Production uses the PostgreSQL migration with JSONB.
CREATE TABLE rg_world_draft_candidates (
    candidate_id VARCHAR(255) NOT NULL,
    tenant_id VARCHAR(255) NOT NULL,
    revision BIGINT NOT NULL,
    candidate_fingerprint VARCHAR(80) NOT NULL,
    canonical_json TEXT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, candidate_id)
);

CREATE TABLE rg_world_draft_redacted_payloads (
    tenant_id VARCHAR(255) NOT NULL,
    candidate_id VARCHAR(255) NOT NULL,
    artifact_revision BIGINT NOT NULL,
    request_fingerprint VARCHAR(80) NOT NULL,
    response_fingerprint VARCHAR(80) NOT NULL,
    pair_fingerprint VARCHAR(80) NOT NULL,
    protected_payload TEXT NOT NULL,
    payload_key_id VARCHAR(64) NOT NULL,
    payload_commitment VARCHAR(80) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    retention_status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    published_world_fingerprint VARCHAR(80),
    published_rule_fingerprint VARCHAR(80),
    publication_receipt_fingerprint VARCHAR(80),
    revoked_at TIMESTAMP,
    PRIMARY KEY (tenant_id, candidate_id, artifact_revision,
                 request_fingerprint, response_fingerprint, pair_fingerprint)
);
CREATE INDEX rg_world_draft_redacted_payloads_expiry_idx
    ON rg_world_draft_redacted_payloads (expires_at);
CREATE INDEX rg_world_draft_redacted_payloads_candidate_idx
    ON rg_world_draft_redacted_payloads (tenant_id, candidate_id, artifact_revision);
CREATE INDEX rg_world_draft_redacted_payloads_retention_idx
    ON rg_world_draft_redacted_payloads (retention_status, expires_at);

CREATE TABLE rg_world_draft_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    candidate_id VARCHAR(255) NOT NULL,
    operation VARCHAR(64) NOT NULL,
    revision BIGINT NOT NULL,
    success BOOLEAN NOT NULL,
    recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rg_world_draft_assets (
    tenant_id VARCHAR(255) NOT NULL,
    candidate_id VARCHAR(255) NOT NULL,
    materialization_fingerprint VARCHAR(80) NOT NULL,
    materialization_revision BIGINT NOT NULL,
    world_fingerprint VARCHAR(80) NOT NULL,
    rule_fingerprint VARCHAR(80) NOT NULL,
    status VARCHAR(16) NOT NULL,
    canonical_json TEXT NOT NULL,
    publication_receipt_fingerprint VARCHAR(80),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, candidate_id, materialization_fingerprint)
);
CREATE INDEX rg_world_draft_assets_status_idx ON rg_world_draft_assets (tenant_id, status, updated_at);

CREATE TABLE rg_world_draft_authority_receipts (
    tenant_id VARCHAR(255) NOT NULL,
    candidate_id VARCHAR(255) NOT NULL,
    receipt_kind VARCHAR(16) NOT NULL,
    receipt_fingerprint VARCHAR(80) NOT NULL,
    canonical_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, candidate_id, receipt_kind, receipt_fingerprint)
);
