CREATE TABLE rg_coverage_inventory_heads (
    tenant_id VARCHAR(255) NOT NULL,
    organization_id VARCHAR(255) NOT NULL,
    project_id VARCHAR(255) NOT NULL,
    environment_id VARCHAR(255) NOT NULL,
    region_id VARCHAR(128) NOT NULL,
    inventory_id VARCHAR(512) NOT NULL,
    revision BIGINT NOT NULL,
    fingerprint VARCHAR(80) NOT NULL,
    target_kind VARCHAR(32) NOT NULL,
    target_id VARCHAR(512) NOT NULL,
    target_revision BIGINT NOT NULL,
    target_fingerprint VARCHAR(80) NOT NULL,
    lifecycle VARCHAR(32) NOT NULL,
    canonical_json CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by VARCHAR(512) NOT NULL,
    PRIMARY KEY (
        tenant_id, organization_id, project_id, environment_id, region_id, inventory_id
    )
);

CREATE TABLE rg_coverage_inventory_revisions (
    tenant_id VARCHAR(255) NOT NULL,
    organization_id VARCHAR(255) NOT NULL,
    project_id VARCHAR(255) NOT NULL,
    environment_id VARCHAR(255) NOT NULL,
    region_id VARCHAR(128) NOT NULL,
    inventory_id VARCHAR(512) NOT NULL,
    revision BIGINT NOT NULL,
    fingerprint VARCHAR(80) NOT NULL,
    target_kind VARCHAR(32) NOT NULL,
    target_id VARCHAR(512) NOT NULL,
    target_revision BIGINT NOT NULL,
    target_fingerprint VARCHAR(80) NOT NULL,
    lifecycle VARCHAR(32) NOT NULL,
    canonical_json CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by VARCHAR(512) NOT NULL,
    PRIMARY KEY (
        tenant_id, organization_id, project_id, environment_id, region_id,
        inventory_id, revision
    )
);

CREATE TABLE rg_coverage_obligation_index (
    tenant_id VARCHAR(255) NOT NULL,
    organization_id VARCHAR(255) NOT NULL,
    project_id VARCHAR(255) NOT NULL,
    environment_id VARCHAR(255) NOT NULL,
    region_id VARCHAR(128) NOT NULL,
    inventory_id VARCHAR(512) NOT NULL,
    inventory_revision BIGINT NOT NULL,
    obligation_id VARCHAR(512) NOT NULL,
    obligation_fingerprint VARCHAR(80) NOT NULL,
    dimension VARCHAR(32) NOT NULL,
    risk VARCHAR(32) NOT NULL,
    owner_id VARCHAR(512) NOT NULL,
    lifecycle VARCHAR(32) NOT NULL,
    source VARCHAR(32) NOT NULL,
    PRIMARY KEY (
        tenant_id, organization_id, project_id, environment_id, region_id,
        inventory_id, inventory_revision, obligation_id
    )
);

CREATE TABLE rg_correctness_outbox (
    sequence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    organization_id VARCHAR(255) NOT NULL,
    project_id VARCHAR(255) NOT NULL,
    environment_id VARCHAR(255) NOT NULL,
    region_id VARCHAR(128) NOT NULL,
    event_id VARCHAR(64) NOT NULL UNIQUE,
    aggregate_kind VARCHAR(64) NOT NULL,
    aggregate_id VARCHAR(512) NOT NULL,
    aggregate_revision BIGINT NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    event_json CLOB NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE rg_correctness_command_receipts (
    tenant_id VARCHAR(255) NOT NULL,
    organization_id VARCHAR(255) NOT NULL,
    project_id VARCHAR(255) NOT NULL,
    environment_id VARCHAR(255) NOT NULL,
    region_id VARCHAR(128) NOT NULL,
    command_kind VARCHAR(64) NOT NULL,
    idempotency_key_fingerprint VARCHAR(80) NOT NULL,
    request_fingerprint VARCHAR(80) NOT NULL,
    result_kind VARCHAR(64) NOT NULL,
    result_id VARCHAR(512) NOT NULL,
    result_revision BIGINT NOT NULL,
    result_fingerprint VARCHAR(80) NOT NULL,
    actor_id VARCHAR(512) NOT NULL,
    receipt_json CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (
        tenant_id, organization_id, project_id, environment_id, region_id,
        command_kind, idempotency_key_fingerprint
    )
);
