CREATE TABLE rg_business_oracle_heads (
    tenant_id VARCHAR(255) NOT NULL,
    organization_id VARCHAR(255) NOT NULL,
    project_id VARCHAR(255) NOT NULL,
    environment_id VARCHAR(255) NOT NULL,
    region_id VARCHAR(128) NOT NULL,
    oracle_id VARCHAR(512) NOT NULL,
    revision BIGINT NOT NULL,
    fingerprint VARCHAR(80) NOT NULL,
    basis_fingerprint VARCHAR(80) NOT NULL,
    target_kind VARCHAR(32) NOT NULL,
    target_id VARCHAR(512) NOT NULL,
    target_revision BIGINT NOT NULL,
    target_fingerprint VARCHAR(80) NOT NULL,
    lifecycle VARCHAR(32) NOT NULL,
    owner_id VARCHAR(512) NOT NULL,
    canonical_json CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by VARCHAR(512) NOT NULL,
    PRIMARY KEY (
        tenant_id, organization_id, project_id, environment_id, region_id, oracle_id
    )
);

CREATE TABLE rg_business_oracle_revisions (
    tenant_id VARCHAR(255) NOT NULL,
    organization_id VARCHAR(255) NOT NULL,
    project_id VARCHAR(255) NOT NULL,
    environment_id VARCHAR(255) NOT NULL,
    region_id VARCHAR(128) NOT NULL,
    oracle_id VARCHAR(512) NOT NULL,
    revision BIGINT NOT NULL,
    fingerprint VARCHAR(80) NOT NULL,
    basis_fingerprint VARCHAR(80) NOT NULL,
    target_kind VARCHAR(32) NOT NULL,
    target_id VARCHAR(512) NOT NULL,
    target_revision BIGINT NOT NULL,
    target_fingerprint VARCHAR(80) NOT NULL,
    lifecycle VARCHAR(32) NOT NULL,
    owner_id VARCHAR(512) NOT NULL,
    canonical_json CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by VARCHAR(512) NOT NULL,
    PRIMARY KEY (
        tenant_id, organization_id, project_id, environment_id, region_id,
        oracle_id, revision
    )
);

CREATE TABLE rg_assertion_set_heads (
    tenant_id VARCHAR(255) NOT NULL,
    organization_id VARCHAR(255) NOT NULL,
    project_id VARCHAR(255) NOT NULL,
    environment_id VARCHAR(255) NOT NULL,
    region_id VARCHAR(128) NOT NULL,
    assertion_set_id VARCHAR(512) NOT NULL,
    revision BIGINT NOT NULL,
    fingerprint VARCHAR(80) NOT NULL,
    target_kind VARCHAR(32) NOT NULL,
    target_id VARCHAR(512) NOT NULL,
    target_revision BIGINT NOT NULL,
    target_fingerprint VARCHAR(80) NOT NULL,
    oracle_id VARCHAR(512) NOT NULL,
    oracle_revision BIGINT NOT NULL,
    oracle_fingerprint VARCHAR(80) NOT NULL,
    lifecycle VARCHAR(32) NOT NULL,
    compatibility_supported BOOLEAN NOT NULL,
    canonical_json CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by VARCHAR(512) NOT NULL,
    PRIMARY KEY (
        tenant_id, organization_id, project_id, environment_id, region_id, assertion_set_id
    )
);

CREATE TABLE rg_assertion_set_revisions (
    tenant_id VARCHAR(255) NOT NULL,
    organization_id VARCHAR(255) NOT NULL,
    project_id VARCHAR(255) NOT NULL,
    environment_id VARCHAR(255) NOT NULL,
    region_id VARCHAR(128) NOT NULL,
    assertion_set_id VARCHAR(512) NOT NULL,
    revision BIGINT NOT NULL,
    fingerprint VARCHAR(80) NOT NULL,
    target_kind VARCHAR(32) NOT NULL,
    target_id VARCHAR(512) NOT NULL,
    target_revision BIGINT NOT NULL,
    target_fingerprint VARCHAR(80) NOT NULL,
    oracle_id VARCHAR(512) NOT NULL,
    oracle_revision BIGINT NOT NULL,
    oracle_fingerprint VARCHAR(80) NOT NULL,
    lifecycle VARCHAR(32) NOT NULL,
    compatibility_supported BOOLEAN NOT NULL,
    canonical_json CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by VARCHAR(512) NOT NULL,
    PRIMARY KEY (
        tenant_id, organization_id, project_id, environment_id, region_id,
        assertion_set_id, revision
    )
);

CREATE TABLE rg_correctness_outbox (
    sequence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    organization_id VARCHAR(255) NOT NULL,
    project_id VARCHAR(255) NOT NULL,
    environment_id VARCHAR(255) NOT NULL,
    region_id VARCHAR(128) NOT NULL,
    event_id VARCHAR(64) NOT NULL UNIQUE,
    aggregate_kind VARCHAR(64) NOT NULL,
    aggregate_id VARCHAR(512) NOT NULL,
    aggregate_revision BIGINT NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    event_json CLOB NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE
);
