CREATE TABLE rg_scenario_draft_set_v2_heads (
    tenant_id VARCHAR(255) NOT NULL,
    organization_id VARCHAR(255) NOT NULL,
    project_id VARCHAR(255) NOT NULL,
    environment_id VARCHAR(255) NOT NULL,
    region_id VARCHAR(128) NOT NULL,
    scenario_draft_set_id VARCHAR(512) NOT NULL,
    revision BIGINT NOT NULL,
    fingerprint VARCHAR(80) NOT NULL,
    target_kind VARCHAR(32) NOT NULL,
    target_id VARCHAR(512) NOT NULL,
    target_revision BIGINT NOT NULL,
    target_fingerprint VARCHAR(80) NOT NULL,
    contract_kind VARCHAR(64) NOT NULL,
    contract_id VARCHAR(512) NOT NULL,
    contract_revision BIGINT NOT NULL,
    contract_fingerprint VARCHAR(80) NOT NULL,
    canonical_json CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by VARCHAR(512) NOT NULL,
    PRIMARY KEY (
        tenant_id, organization_id, project_id, environment_id, region_id,
        scenario_draft_set_id
    )
);

CREATE TABLE rg_scenario_draft_set_v2_revisions (
    tenant_id VARCHAR(255) NOT NULL,
    organization_id VARCHAR(255) NOT NULL,
    project_id VARCHAR(255) NOT NULL,
    environment_id VARCHAR(255) NOT NULL,
    region_id VARCHAR(128) NOT NULL,
    scenario_draft_set_id VARCHAR(512) NOT NULL,
    revision BIGINT NOT NULL,
    fingerprint VARCHAR(80) NOT NULL,
    target_kind VARCHAR(32) NOT NULL,
    target_id VARCHAR(512) NOT NULL,
    target_revision BIGINT NOT NULL,
    target_fingerprint VARCHAR(80) NOT NULL,
    contract_kind VARCHAR(64) NOT NULL,
    contract_id VARCHAR(512) NOT NULL,
    contract_revision BIGINT NOT NULL,
    contract_fingerprint VARCHAR(80) NOT NULL,
    canonical_json CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by VARCHAR(512) NOT NULL,
    PRIMARY KEY (
        tenant_id, organization_id, project_id, environment_id, region_id,
        scenario_draft_set_id, revision
    )
);

CREATE TABLE rg_scenario_case_v2_index (
    tenant_id VARCHAR(255) NOT NULL,
    organization_id VARCHAR(255) NOT NULL,
    project_id VARCHAR(255) NOT NULL,
    environment_id VARCHAR(255) NOT NULL,
    region_id VARCHAR(128) NOT NULL,
    scenario_draft_set_id VARCHAR(512) NOT NULL,
    scenario_draft_set_revision BIGINT NOT NULL,
    case_id VARCHAR(512) NOT NULL,
    case_fingerprint VARCHAR(80) NOT NULL,
    lifecycle VARCHAR(32) NOT NULL,
    risk VARCHAR(32) NOT NULL,
    owner_id VARCHAR(512) NOT NULL,
    owner_kind VARCHAR(32) NOT NULL,
    case_type VARCHAR(32) NOT NULL,
    case_name VARCHAR(1024) NOT NULL,
    business_intent VARCHAR(16384) NOT NULL,
    obligation_count INTEGER NOT NULL,
    oracle_count INTEGER NOT NULL,
    assertion_set_count INTEGER NOT NULL,
    dependency_count INTEGER NOT NULL,
    review_status VARCHAR(32) NOT NULL,
    tags_json CLOB NOT NULL,
    canonical_json CLOB NOT NULL,
    PRIMARY KEY (
        tenant_id, organization_id, project_id, environment_id, region_id,
        scenario_draft_set_id, scenario_draft_set_revision, case_id
    )
);

CREATE TABLE rg_scenario_case_obligation_ref_index (
    tenant_id VARCHAR(255) NOT NULL,
    organization_id VARCHAR(255) NOT NULL,
    project_id VARCHAR(255) NOT NULL,
    environment_id VARCHAR(255) NOT NULL,
    region_id VARCHAR(128) NOT NULL,
    scenario_draft_set_id VARCHAR(512) NOT NULL,
    scenario_draft_set_revision BIGINT NOT NULL,
    case_id VARCHAR(512) NOT NULL,
    case_lifecycle VARCHAR(32) NOT NULL,
    inventory_id VARCHAR(512) NOT NULL,
    inventory_revision BIGINT NOT NULL,
    inventory_fingerprint VARCHAR(80) NOT NULL,
    obligation_id VARCHAR(512) NOT NULL,
    obligation_fingerprint VARCHAR(80) NOT NULL,
    PRIMARY KEY (
        tenant_id, organization_id, project_id, environment_id, region_id,
        scenario_draft_set_id, scenario_draft_set_revision, case_id,
        inventory_id, inventory_revision, obligation_id
    )
);

CREATE TABLE rg_correctness_outbox (
    sequence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    organization_id VARCHAR(255) NOT NULL,
    project_id VARCHAR(255) NOT NULL,
    environment_id VARCHAR(255) NOT NULL,
    region_id VARCHAR(128) NOT NULL,
    event_id VARCHAR(64) NOT NULL UNIQUE,
    aggregate_kind VARCHAR(64) NOT NULL,
    aggregate_id VARCHAR(512) NOT NULL,
    aggregate_revision BIGINT NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    event_json CLOB NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE
);
