package com.leanowtech.bloge.gateway.integration;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

import jakarta.annotation.PostConstruct;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.List;

/** H2-backed transactional outbox with a global monotonic stream sequence. */
public class DatabaseIntegrationChangeEventOutbox implements IntegrationChangeEventOutbox {
    private static final String CREATE_TABLE = """
            CREATE TABLE IF NOT EXISTS integration_change_outbox (
                stream_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                event_id VARCHAR(96) NOT NULL UNIQUE,
                tenant_id VARCHAR(255) NOT NULL,
                environment_id VARCHAR(255) NOT NULL,
                event_json CLOB NOT NULL
            )
            """;
    private static final String CREATE_SCOPE_INDEX = """
            CREATE INDEX IF NOT EXISTS idx_integration_outbox_scope_sequence
            ON integration_change_outbox (tenant_id, environment_id, stream_sequence)
            """;
    private static final String INSERT = """
            INSERT INTO integration_change_outbox (event_id, tenant_id, environment_id, event_json)
            VALUES (?, ?, ?, ?)
            """;
    private static final String READ = """
            SELECT stream_sequence, event_json
            FROM integration_change_outbox
            WHERE stream_sequence > ? AND stream_sequence <= ?
              AND (tenant_id = ? OR tenant_id = '*')
              AND (environment_id = ? OR environment_id = '*')
            ORDER BY stream_sequence ASC
            LIMIT ?
            """;
    private static final String COUNT_AFTER = """
            SELECT COUNT(*)
            FROM integration_change_outbox
            WHERE stream_sequence > ? AND stream_sequence <= ?
              AND (tenant_id = ? OR tenant_id = '*')
              AND (environment_id = ? OR environment_id = '*')
            """;

    private final JdbcTemplate jdbc;
    private final ObjectMapper objectMapper;

    public DatabaseIntegrationChangeEventOutbox(JdbcTemplate jdbc, ObjectMapper objectMapper) {
        this.jdbc = jdbc;
        this.objectMapper = objectMapper;
    }

    @PostConstruct
    void init() {
        jdbc.execute(CREATE_TABLE);
        jdbc.execute(CREATE_SCOPE_INDEX);
    }

    @Override
    public IntegrationChangeEvent append(IntegrationChangeEvent event) {
        if (event == null || !event.fingerprintVerified()) {
            throw new IllegalArgumentException("A fingerprint-verified integration change event is required");
        }
        String json;
        try {
            json = objectMapper.writeValueAsString(event);
        } catch (JsonProcessingException exception) {
            throw new IllegalStateException("Failed to serialize integration change event", exception);
        }
        KeyHolder keys = new GeneratedKeyHolder();
        jdbc.update(connection -> {
            PreparedStatement statement = connection.prepareStatement(INSERT, Statement.RETURN_GENERATED_KEYS);
            statement.setString(1, event.eventId());
            statement.setString(2, event.tenantId());
            statement.setString(3, event.environmentId());
            statement.setString(4, json);
            return statement;
        }, keys);
        Number key = keys.getKey();
        if (key == null) {
            throw new IllegalStateException("Integration outbox did not return a stream sequence");
        }
        return event.withStreamSequence(key.longValue());
    }

    @Override
    public List<IntegrationChangeEvent> read(long afterSequence,
                                             long throughSequence,
                                             String tenantId,
                                             String environmentId,
                                             int limit) {
        long after = Math.max(0, afterSequence);
        long through = Math.max(after, throughSequence);
        return jdbc.query(READ, (rs, rowNum) -> readEvent(rs.getString("event_json"))
                        .withStreamSequence(rs.getLong("stream_sequence")),
                after, through, scope(tenantId), scope(environmentId), Math.max(1, Math.min(500, limit)));
    }

    @Override
    public boolean hasAfter(long afterSequence,
                            long throughSequence,
                            String tenantId,
                            String environmentId) {
        long after = Math.max(0, afterSequence);
        long through = Math.max(after, throughSequence);
        Long count = jdbc.queryForObject(COUNT_AFTER, Long.class, after, through, scope(tenantId),
                scope(environmentId));
        return count != null && count > 0;
    }

    @Override
    public long highWaterSequence() {
        Long value = jdbc.queryForObject(
                "SELECT COALESCE(MAX(stream_sequence), 0) FROM integration_change_outbox", Long.class);
        return value == null ? 0 : value;
    }

    @Override
    public boolean available() {
        return true;
    }

    private IntegrationChangeEvent readEvent(String json) {
        try {
            IntegrationChangeEvent event = objectMapper.readValue(json, IntegrationChangeEvent.class);
            if (!event.fingerprintVerified()) {
                throw new IllegalStateException("Integration change event fingerprint verification failed");
            }
            return event;
        } catch (JsonProcessingException exception) {
            throw new IllegalStateException("Failed to deserialize integration change event", exception);
        }
    }

    private static String scope(String value) {
        return value == null || value.isBlank() ? IntegrationChangeEvent.GLOBAL_SCOPE : value.trim();
    }
}
