package com.leanowtech.bloge.gateway.integration;

import jakarta.annotation.PostConstruct;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.List;

/** H2-backed append-only integration authentication audit repository. */
public final class DatabaseIntegrationAccessAuditRepository implements IntegrationAccessAuditRepository {
    private final JdbcTemplate jdbc;

    public DatabaseIntegrationAccessAuditRepository(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    @PostConstruct
    void init() {
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS integration_access_audit (
                    sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    correlation_id VARCHAR(160) NOT NULL,
                    identity_id VARCHAR(255) NOT NULL,
                    tenant_id VARCHAR(255) NOT NULL,
                    environment_id VARCHAR(255) NOT NULL,
                    operation VARCHAR(96) NOT NULL,
                    purpose VARCHAR(128) NOT NULL,
                    outcome VARCHAR(32) NOT NULL,
                    reason_code VARCHAR(160) NOT NULL
                )
                """);
        jdbc.execute("""
                CREATE INDEX IF NOT EXISTS idx_integration_access_audit_scope_time
                ON integration_access_audit (tenant_id, environment_id, occurred_at)
                """);
    }

    @Override
    public IntegrationAccessAuditRecord append(IntegrationAccessAuditRecord record) {
        if (record == null) {
            throw new IllegalArgumentException("Integration access audit record is required");
        }
        KeyHolder keys = new GeneratedKeyHolder();
        jdbc.update(connection -> {
            PreparedStatement statement = connection.prepareStatement("""
                    INSERT INTO integration_access_audit (
                        occurred_at, correlation_id, identity_id, tenant_id, environment_id,
                        operation, purpose, outcome, reason_code
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """, Statement.RETURN_GENERATED_KEYS);
            statement.setTimestamp(1, Timestamp.from(record.occurredAt()));
            statement.setString(2, record.correlationId());
            statement.setString(3, record.identityId());
            statement.setString(4, record.tenantId());
            statement.setString(5, record.environmentId());
            statement.setString(6, record.operation());
            statement.setString(7, record.purpose());
            statement.setString(8, record.outcome());
            statement.setString(9, record.reasonCode());
            return statement;
        }, keys);
        Number key = keys.getKey();
        if (key == null) {
            throw new IllegalStateException("Integration audit insert did not return a sequence");
        }
        return record.withSequence(key.longValue());
    }

    @Override
    public List<IntegrationAccessAuditRecord> recent(int limit) {
        return jdbc.query("""
                        SELECT sequence, occurred_at, correlation_id, identity_id, tenant_id, environment_id,
                               operation, purpose, outcome, reason_code
                        FROM integration_access_audit
                        ORDER BY sequence DESC
                        LIMIT ?
                        """, (rs, rowNum) -> new IntegrationAccessAuditRecord(
                        rs.getLong("sequence"), rs.getTimestamp("occurred_at").toInstant(),
                        rs.getString("correlation_id"), rs.getString("identity_id"), rs.getString("tenant_id"),
                        rs.getString("environment_id"), rs.getString("operation"), rs.getString("purpose"),
                        rs.getString("outcome"), rs.getString("reason_code")),
                Math.max(1, Math.min(1000, limit)));
    }
}
