package com.leanowtech.bloge.gateway.integration;

import java.util.Locale;
import java.util.Set;

/** Central operation-to-purpose policy for the Tool Studio integration surface. */
public enum IntegrationOperation {
    DRAFT_EXPORT(Set.of("GOVERNANCE_EVIDENCE_INGESTION", "CHANGE_SYNC")),
    WORKBOOK_EXPORT(Set.of("GOVERNANCE_EVIDENCE_INGESTION", "WORKBOOK_SYNC")),
    RUN_EVIDENCE_READ(Set.of("GOVERNANCE_EVIDENCE_INGESTION")),
    SIDE_EFFECT_RECONCILIATION_READ(Set.of(
            "GOVERNANCE_EVIDENCE_INGESTION", "SIDE_EFFECT_RECONCILIATION")),
    SIDE_EFFECT_RECONCILIATION_EXECUTE(Set.of("SIDE_EFFECT_RECONCILIATION")),
    RECORDED_PAYLOAD_READ(Set.of("GOVERNANCE_EVIDENCE_INGESTION", "PAYLOAD_REPLAY")),
    RECORDED_REPLAY(Set.of("PAYLOAD_REPLAY")),
    PAYLOAD_RETENTION_READ(Set.of("GOVERNANCE_EVIDENCE_INGESTION", "PAYLOAD_RETENTION_ADMIN", "LEGAL_HOLD")),
    PAYLOAD_RETENTION_ADMIN(Set.of("PAYLOAD_RETENTION_ADMIN")),
    PAYLOAD_LEGAL_HOLD(Set.of("LEGAL_HOLD")),
    EVIDENCE_TRUST_PUBLISH(Set.of("EVIDENCE_TRUST_ADMIN")),
    GATE_RESULT_WRITE(Set.of("GOVERNANCE_GATE_FEEDBACK")),
    GATE_RESULT_READ(Set.of("GOVERNANCE_EVIDENCE_INGESTION", "GOVERNANCE_GATE_FEEDBACK")),
    CHANGE_SYNC(Set.of("CHANGE_SYNC")),
    CAPABILITY_SNAPSHOT_READ(Set.of(
            "CHANGE_SYNC", "GOVERNANCE_EVIDENCE_INGESTION", "MIRROR_REHEARSAL")),
    CAPABILITY_SNAPSHOT_WRITE(Set.of("CAPABILITY_PROJECTION", "CHANGE_SYNC")),
    CAPABILITY_CLOSURE_PROJECTION(Set.of("CAPABILITY_PROJECTION")),
    CAPABILITY_LIFECYCLE_TRANSITION(Set.of("CAPABILITY_GOVERNANCE")),
    MIRROR_PLAN_COMPILE(Set.of("MIRROR_REHEARSAL")),
    MIRROR_PLAN_READ(Set.of("MIRROR_REHEARSAL")),
    MIRROR_SCENARIO_ARTIFACT_WRITE(Set.of("MIRROR_REHEARSAL")),
    MIRROR_SCENARIO_ARTIFACT_READ(Set.of("MIRROR_REHEARSAL")),
    MIRROR_REHEARSAL_PLAN_COMPILE(Set.of("MIRROR_REHEARSAL")),
    MIRROR_REHEARSAL_PLAN_READ(Set.of("MIRROR_REHEARSAL")),
    MIRROR_REHEARSAL_EXECUTE(Set.of("MIRROR_REHEARSAL")),
    MIRROR_REHEARSAL_BATCH_SUBMIT(Set.of("MIRROR_REHEARSAL")),
    MIRROR_REHEARSAL_BATCH_READ(Set.of(
            "MIRROR_REHEARSAL", "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_REHEARSAL_BATCH_EVIDENCE_READ(Set.of(
            "MIRROR_REHEARSAL", "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_REHEARSAL_BATCH_WORKBOOK_READ(Set.of(
            "MIRROR_REHEARSAL", "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_REHEARSAL_REMEDIATION_PREVIEW(Set.of(
            "MIRROR_REHEARSAL_REMEDIATION")),
    MIRROR_REHEARSAL_REMEDIATION_APPROVE(Set.of(
            "MIRROR_REHEARSAL_REMEDIATION")),
    MIRROR_REHEARSAL_REMEDIATION_SUBMIT(Set.of(
            "MIRROR_REHEARSAL_REMEDIATION")),
    MIRROR_REHEARSAL_REMEDIATION_READ(Set.of(
            "MIRROR_REHEARSAL_REMEDIATION")),
    MIRROR_REHEARSAL_REMEDIATION_COMPARISON_READ(Set.of(
            "MIRROR_REHEARSAL_REMEDIATION")),
    MIRROR_REHEARSAL_BATCH_CANCEL(Set.of("MIRROR_REHEARSAL")),
    MIRROR_REHEARSAL_BATCH_FINALIZATION_REMEDIATE(
            Set.of("MIRROR_REHEARSAL_FINALIZATION_ADMIN")),
    MIRROR_REHEARSAL_BATCH_FINALIZATION_HEALTH_READ(Set.of(
            "MIRROR_REHEARSAL",
            "GOVERNANCE_EVIDENCE_INGESTION",
            "MIRROR_REHEARSAL_FINALIZATION_ADMIN")),
    MIRROR_REHEARSAL_EVIDENCE_READ(Set.of(
            "MIRROR_REHEARSAL", "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_REHEARSAL_WORKBOOK_READ(Set.of(
            "MIRROR_REHEARSAL", "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_REHEARSAL_RETENTION_READ(Set.of(
            "MIRROR_REHEARSAL", "GOVERNANCE_EVIDENCE_INGESTION",
            "PAYLOAD_RETENTION_ADMIN", "LEGAL_HOLD")),
    MIRROR_REHEARSAL_LEGAL_HOLD(Set.of("LEGAL_HOLD")),
    MIRROR_REHEARSAL_RETENTION_ADMIN(Set.of(
            "PAYLOAD_RETENTION_ADMIN")),
    MIRROR_EXECUTION_CREATE(Set.of("MIRROR_REHEARSAL")),
    MIRROR_RUN_READ(Set.of("MIRROR_REHEARSAL")),
    MIRROR_EVIDENCE_READ(Set.of("MIRROR_REHEARSAL")),
    MIRROR_SESSION_CREATE(Set.of("MIRROR_REHEARSAL")),
    MIRROR_SESSION_READ(Set.of("MIRROR_REHEARSAL")),
    MIRROR_SESSION_COMMAND(Set.of("MIRROR_REHEARSAL")),
    MIRROR_SESSION_CHECKPOINT(Set.of("MIRROR_REHEARSAL")),
    MIRROR_SESSION_RECOVER(Set.of("MIRROR_REHEARSAL")),
    MIRROR_SESSION_DESTROY(Set.of("MIRROR_REHEARSAL")),
    MIRROR_ISOLATION_AUTHORITY_PUBLISH(Set.of("MIRROR_TRUST_ADMIN")),
    MIRROR_ISOLATION_AUTHORITY_READ(Set.of(
            "MIRROR_TRUST_DISTRIBUTION", "MIRROR_REHEARSAL")),
    MIRROR_SHADOW_AUTHORITY_KEY_SET_PUBLISH(Set.of("MIRROR_TRUST_ADMIN")),
    MIRROR_SHADOW_AUTHORITY_KEY_SET_READ(Set.of(
            "MIRROR_TRUST_DISTRIBUTION", "MIRROR_SHADOW")),
    MIRROR_ISOLATION_ATTESTATION_ADMIN(Set.of("MIRROR_TRUST_ADMIN")),
    MIRROR_ISOLATION_ATTESTATION_READ(Set.of(
            "MIRROR_TRUST_DISTRIBUTION", "MIRROR_REHEARSAL")),
    MIRROR_OBSERVATION_INGEST(Set.of("MIRROR_CORPUS_INGESTION")),
    MIRROR_OBSERVATION_REVIEW(Set.of("MIRROR_CORPUS_GOVERNANCE")),
    MIRROR_CORPUS_CANDIDATE_CREATE(Set.of("MIRROR_CORPUS_GOVERNANCE")),
    MIRROR_CORPUS_PUBLISH(Set.of("MIRROR_CORPUS_GOVERNANCE")),
    MIRROR_CORPUS_TRAJECTORY_PUBLISH(Set.of("MIRROR_CORPUS_GOVERNANCE")),
    MIRROR_CORPUS_CLUSTER_PUBLISH(Set.of("MIRROR_CORPUS_GOVERNANCE")),
    MIRROR_FIDELITY_INVENTORY_WRITE(Set.of("MIRROR_FIDELITY_GOVERNANCE")),
    MIRROR_FIDELITY_INVENTORY_READ(Set.of(
            "MIRROR_FIDELITY_GOVERNANCE",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_FIDELITY_PROFILE_READ(Set.of(
            "MIRROR_FIDELITY_GOVERNANCE",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_SHADOW_JOB_SUBMIT(Set.of("MIRROR_SHADOW")),
    MIRROR_SHADOW_JOB_READ(Set.of(
            "MIRROR_SHADOW",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_SHADOW_COMPARISON_READ(Set.of(
            "MIRROR_SHADOW",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_SHADOW_LIFECYCLE_READ(Set.of(
            "MIRROR_SHADOW",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    TEST_EXECUTION(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_EXECUTION_CREATE(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_EXECUTION_READ(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_OWNER_CLAIM(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_WORKER_ACQUISITION(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_RECOVERY_CONTROL(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_RECOVERY_STEP(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_RECOVERY_SEQUENCE(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_PROJECTION_MAINTENANCE(Set.of("TEST_RUNTIME_MAINTENANCE")),
    TEST_DURABLE_WORKER_QUARANTINE_MAINTENANCE(Set.of("TEST_RUNTIME_MAINTENANCE")),
    TEST_DURABLE_REQUEST_INDEX_ROLLOUT(Set.of("TEST_RUNTIME_MAINTENANCE")),
    TEST_TARGET_READ(Set.of("TEST_EXECUTION", "TEST_FIXTURE_READ", "TEST_FIXTURE_WRITE",
            "TEST_SUITE_READ", "TEST_SUITE_WRITE")),
    TEST_FIXTURE_READ(Set.of("TEST_FIXTURE_READ")),
    TEST_FIXTURE_WRITE(Set.of("TEST_FIXTURE_WRITE", "TEST_REPLAY")),
    TEST_REPLAY_READ(Set.of("TEST_REPLAY")),
    TEST_REPLAY_WRITE(Set.of("TEST_REPLAY")),
    TEST_SUITE_EXECUTION(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_SUITE_STABILITY_JOB_SUBMIT(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_SUITE_STABILITY_JOB_READ(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_SUITE_STABILITY_JOB_CANCEL(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_SUITE_STABILITY_TREND_READ(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_SUITE_READ(Set.of("TEST_SUITE_READ")),
    TEST_SUITE_WRITE(Set.of("TEST_SUITE_WRITE"));

    private final Set<String> acceptedPurposes;

    IntegrationOperation(Set<String> acceptedPurposes) {
        this.acceptedPurposes = Set.copyOf(acceptedPurposes);
    }

    public boolean accepts(String purpose) {
        return acceptedPurposes.contains(purpose == null ? "" : purpose.trim().toUpperCase(Locale.ROOT));
    }

    public Set<String> acceptedPurposes() {
        return acceptedPurposes;
    }
}
