package com.leanowtech.bloge.gateway.integration;

import java.util.Locale;
import java.util.Set;

/** Central operation-to-purpose policy for the Tool Studio integration surface. */
public enum IntegrationOperation {
    DRAFT_EXPORT(Set.of("GOVERNANCE_EVIDENCE_INGESTION", "CHANGE_SYNC")),
    WORKBOOK_EXPORT(Set.of("GOVERNANCE_EVIDENCE_INGESTION", "WORKBOOK_SYNC")),
    RUN_EVIDENCE_READ(Set.of("GOVERNANCE_EVIDENCE_INGESTION")),
    SIDE_EFFECT_RECONCILIATION_READ(Set.of(
            "GOVERNANCE_EVIDENCE_INGESTION", "SIDE_EFFECT_RECONCILIATION")),
    SIDE_EFFECT_RECONCILIATION_EXECUTE(Set.of("SIDE_EFFECT_RECONCILIATION")),
    RECORDED_PAYLOAD_READ(Set.of("GOVERNANCE_EVIDENCE_INGESTION", "PAYLOAD_REPLAY")),
    RECORDED_REPLAY(Set.of("PAYLOAD_REPLAY")),
    PAYLOAD_RETENTION_READ(Set.of("GOVERNANCE_EVIDENCE_INGESTION", "PAYLOAD_RETENTION_ADMIN", "LEGAL_HOLD")),
    PAYLOAD_RETENTION_ADMIN(Set.of("PAYLOAD_RETENTION_ADMIN")),
    PAYLOAD_LEGAL_HOLD(Set.of("LEGAL_HOLD")),
    EVIDENCE_TRUST_PUBLISH(Set.of("EVIDENCE_TRUST_ADMIN")),
    GATE_RESULT_WRITE(Set.of("GOVERNANCE_GATE_FEEDBACK")),
    GATE_RESULT_READ(Set.of("GOVERNANCE_EVIDENCE_INGESTION", "GOVERNANCE_GATE_FEEDBACK")),
    CHANGE_SYNC(Set.of("CHANGE_SYNC")),
    CAPABILITY_SNAPSHOT_READ(Set.of(
            "CHANGE_SYNC", "GOVERNANCE_EVIDENCE_INGESTION", "MIRROR_REHEARSAL")),
    CAPABILITY_SNAPSHOT_WRITE(Set.of("CAPABILITY_PROJECTION", "CHANGE_SYNC")),
    CAPABILITY_CLOSURE_PROJECTION(Set.of("CAPABILITY_PROJECTION")),
    CAPABILITY_LIFECYCLE_TRANSITION(Set.of("CAPABILITY_GOVERNANCE")),
    CAPABILITY_STUDIO_REHEARSAL(Set.of("CAPABILITY_STUDIO_REHEARSAL")),
    CAPABILITY_STUDIO_EVIDENCE_READ(Set.of("CAPABILITY_STUDIO_REHEARSAL")),
    CAPABILITY_STUDIO_SCENARIO_QUALITY_READ(Set.of("CAPABILITY_STUDIO_REHEARSAL")),
    MIRROR_PLAN_COMPILE(Set.of("MIRROR_REHEARSAL")),
    MIRROR_PLAN_READ(Set.of("MIRROR_REHEARSAL")),
    MIRROR_SCENARIO_ARTIFACT_WRITE(Set.of("MIRROR_REHEARSAL")),
    MIRROR_SCENARIO_ARTIFACT_READ(Set.of("MIRROR_REHEARSAL")),
    MIRROR_REHEARSAL_PLAN_COMPILE(Set.of("MIRROR_REHEARSAL")),
    MIRROR_REHEARSAL_PLAN_READ(Set.of("MIRROR_REHEARSAL")),
    MIRROR_REHEARSAL_EXECUTE(Set.of("MIRROR_REHEARSAL")),
    MIRROR_REHEARSAL_BATCH_SUBMIT(Set.of("MIRROR_REHEARSAL")),
    MIRROR_REHEARSAL_BATCH_READ(Set.of(
            "MIRROR_REHEARSAL", "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_REHEARSAL_BATCH_EVIDENCE_READ(Set.of(
            "MIRROR_REHEARSAL", "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_REHEARSAL_BATCH_WORKBOOK_READ(Set.of(
            "MIRROR_REHEARSAL", "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_REHEARSAL_REMEDIATION_PREVIEW(Set.of(
            "MIRROR_REHEARSAL_REMEDIATION")),
    MIRROR_REHEARSAL_REMEDIATION_APPROVE(Set.of(
            "MIRROR_REHEARSAL_REMEDIATION")),
    MIRROR_REHEARSAL_REMEDIATION_SUBMIT(Set.of(
            "MIRROR_REHEARSAL_REMEDIATION")),
    MIRROR_REHEARSAL_REMEDIATION_READ(Set.of(
            "MIRROR_REHEARSAL_REMEDIATION")),
    MIRROR_REHEARSAL_REMEDIATION_COMPARISON_READ(Set.of(
            "MIRROR_REHEARSAL_REMEDIATION")),
    MIRROR_REHEARSAL_BATCH_CANCEL(Set.of("MIRROR_REHEARSAL")),
    MIRROR_REHEARSAL_BATCH_FINALIZATION_REMEDIATE(
            Set.of("MIRROR_REHEARSAL_FINALIZATION_ADMIN")),
    MIRROR_REHEARSAL_BATCH_FINALIZATION_HEALTH_READ(Set.of(
            "MIRROR_REHEARSAL",
            "GOVERNANCE_EVIDENCE_INGESTION",
            "MIRROR_REHEARSAL_FINALIZATION_ADMIN")),
    MIRROR_REHEARSAL_EVIDENCE_READ(Set.of(
            "MIRROR_REHEARSAL", "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_REHEARSAL_WORKBOOK_READ(Set.of(
            "MIRROR_REHEARSAL", "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_REHEARSAL_RETENTION_READ(Set.of(
            "MIRROR_REHEARSAL", "GOVERNANCE_EVIDENCE_INGESTION",
            "PAYLOAD_RETENTION_ADMIN", "LEGAL_HOLD")),
    MIRROR_REHEARSAL_LEGAL_HOLD(Set.of("LEGAL_HOLD")),
    MIRROR_REHEARSAL_RETENTION_ADMIN(Set.of(
            "PAYLOAD_RETENTION_ADMIN")),
    MIRROR_EXECUTION_CREATE(Set.of("MIRROR_REHEARSAL")),
    MIRROR_RUN_READ(Set.of("MIRROR_REHEARSAL")),
    MIRROR_EVIDENCE_READ(Set.of("MIRROR_REHEARSAL")),
    MIRROR_SESSION_CREATE(Set.of("MIRROR_REHEARSAL")),
    MIRROR_SESSION_READ(Set.of("MIRROR_REHEARSAL")),
    MIRROR_SESSION_COMMAND(Set.of("MIRROR_REHEARSAL")),
    MIRROR_SESSION_CHECKPOINT(Set.of("MIRROR_REHEARSAL")),
    MIRROR_SESSION_RECOVER(Set.of("MIRROR_REHEARSAL")),
    MIRROR_SESSION_DESTROY(Set.of("MIRROR_REHEARSAL")),
    MIRROR_ISOLATION_AUTHORITY_PUBLISH(Set.of("MIRROR_TRUST_ADMIN")),
    MIRROR_ISOLATION_AUTHORITY_READ(Set.of(
            "MIRROR_TRUST_DISTRIBUTION", "MIRROR_REHEARSAL")),
    MIRROR_SHADOW_AUTHORITY_KEY_SET_PUBLISH(Set.of("MIRROR_TRUST_ADMIN")),
    MIRROR_SHADOW_AUTHORITY_KEY_SET_READ(Set.of(
            "MIRROR_TRUST_DISTRIBUTION", "MIRROR_SHADOW")),
    MIRROR_SHADOW_SOURCE_BINDING_PUBLISH(Set.of(
            "MIRROR_SHADOW_SOURCE_ADMIN")),
    MIRROR_SHADOW_SOURCE_BINDING_READ(Set.of(
            "MIRROR_SHADOW",
            "MIRROR_SHADOW_SOURCE_ADMIN",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_SHADOW_SOURCE_RESOLUTION_READ(Set.of(
            "MIRROR_SHADOW",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_SHADOW_ONLINE_BASELINE_CAPABILITY(Set.of(
            "MIRROR_SHADOW")),
    MIRROR_SHADOW_ONLINE_BASELINE_EXECUTE(Set.of(
            "MIRROR_SHADOW")),
    MIRROR_SHADOW_ONLINE_BASELINE_READ(Set.of(
            "MIRROR_SHADOW",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_SHADOW_ONLINE_CANDIDATE_CAPABILITY(Set.of(
            "MIRROR_SHADOW")),
    MIRROR_SHADOW_ONLINE_CANDIDATE_EXECUTE(Set.of(
            "MIRROR_SHADOW")),
    MIRROR_SHADOW_ONLINE_CANDIDATE_READ(Set.of(
            "MIRROR_SHADOW",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_ISOLATION_ATTESTATION_ADMIN(Set.of("MIRROR_TRUST_ADMIN")),
    MIRROR_ISOLATION_ATTESTATION_READ(Set.of(
            "MIRROR_TRUST_DISTRIBUTION", "MIRROR_REHEARSAL")),
    MIRROR_OBSERVATION_INGEST(Set.of("MIRROR_CORPUS_INGESTION")),
    MIRROR_OBSERVATION_REVIEW(Set.of("MIRROR_CORPUS_GOVERNANCE")),
    MIRROR_CORPUS_CANDIDATE_CREATE(Set.of("MIRROR_CORPUS_GOVERNANCE")),
    MIRROR_CORPUS_PUBLISH(Set.of("MIRROR_CORPUS_GOVERNANCE")),
    MIRROR_CORPUS_TRAJECTORY_PUBLISH(Set.of("MIRROR_CORPUS_GOVERNANCE")),
    MIRROR_CORPUS_CLUSTER_PUBLISH(Set.of("MIRROR_CORPUS_GOVERNANCE")),
    MIRROR_FIDELITY_INVENTORY_WRITE(Set.of("MIRROR_FIDELITY_GOVERNANCE")),
    MIRROR_FIDELITY_INVENTORY_READ(Set.of(
            "MIRROR_FIDELITY_GOVERNANCE",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_FIDELITY_PROFILE_READ(Set.of(
            "MIRROR_FIDELITY_GOVERNANCE",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_OUTCOME_OBSERVATION_INGEST(Set.of(
            "MIRROR_OUTCOME_INGESTION")),
    MIRROR_OUTCOME_OBSERVATION_READ(Set.of(
            "MIRROR_OUTCOME_INGESTION",
            "MIRROR_FIDELITY_GOVERNANCE",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_OUTCOME_LIFECYCLE_READ(Set.of(
            "MIRROR_OUTCOME_INGESTION",
            "MIRROR_FIDELITY_GOVERNANCE",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_OUTCOME_SOURCE_CONTROL(Set.of(
            "MIRROR_OUTCOME_SOURCE_ADMIN")),
    MIRROR_OUTCOME_SOURCE_CHECKPOINT_READ(Set.of(
            "MIRROR_OUTCOME_SOURCE_ADMIN",
            "MIRROR_FIDELITY_GOVERNANCE",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_OUTCOME_POPULATION_INGEST(Set.of(
            "MIRROR_OUTCOME_SELECTION")),
    MIRROR_OUTCOME_DISPOSITION_INGEST(Set.of(
            "MIRROR_OUTCOME_DISPOSITION")),
    MIRROR_OUTCOME_POPULATION_ASSESS(Set.of(
            "MIRROR_FIDELITY_GOVERNANCE")),
    MIRROR_OUTCOME_CONTINUOUS_ASSESSMENT_REGISTER(Set.of(
            "MIRROR_FIDELITY_GOVERNANCE")),
    MIRROR_OUTCOME_CONTINUOUS_ASSESSMENT_READ(Set.of(
            "MIRROR_FIDELITY_GOVERNANCE",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_OUTCOME_CONTINUOUS_ASSESSMENT_LIFECYCLE_READ(Set.of(
            "MIRROR_FIDELITY_GOVERNANCE",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_OUTCOME_CONTINUOUS_ASSESSMENT_REMEDIATE(Set.of(
            "MIRROR_OUTCOME_CONTINUOUS_ASSESSMENT_ADMIN")),
    MIRROR_OUTCOME_POPULATION_READ(Set.of(
            "MIRROR_OUTCOME_SELECTION",
            "MIRROR_OUTCOME_DISPOSITION",
            "MIRROR_FIDELITY_GOVERNANCE",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_SHADOW_JOB_SUBMIT(Set.of("MIRROR_SHADOW")),
    MIRROR_SHADOW_JOB_READ(Set.of(
            "MIRROR_SHADOW",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_SHADOW_COMPARISON_READ(Set.of(
            "MIRROR_SHADOW",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    MIRROR_SHADOW_LIFECYCLE_READ(Set.of(
            "MIRROR_SHADOW",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    TEST_EXECUTION(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    AUTHORING_DRAFT_READ(Set.of(
            "TEST_SUITE_READ", "TEST_SUITE_WRITE", "GOVERNANCE_EVIDENCE_INGESTION")),
    AUTHORING_DRAFT_WRITE(Set.of("TEST_SUITE_WRITE")),
    AUTHORING_DRAFT_COMMIT(Set.of("TEST_SCENARIO_PUBLISH")),
    AUTHORING_API_CONNECTION_READ(Set.of("API_RESOURCE_AUTHORING")),
    AUTHORING_API_CONNECTION_WRITE(Set.of("API_RESOURCE_AUTHORING")),
    AUTHORING_API_CONNECTION_CHECK(Set.of("API_RESOURCE_AUTHORING")),
    AUTHORING_API_RESOURCE_WRITE(Set.of("API_RESOURCE_AUTHORING")),
    AUTHORING_FIXTURE_SET_READ(Set.of("API_RESOURCE_AUTHORING")),
    AUTHORING_SIMULATION_EXECUTE(Set.of("API_RESOURCE_AUTHORING")),
    AUTHORING_SIMULATION_READ(Set.of("API_RESOURCE_AUTHORING")),
    AUTHORING_TEST_EXECUTE(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    AUTHORING_TEST_EVIDENCE_READ(Set.of(
            "TEST_EXECUTION", "TEST_SUITE_READ", "GOVERNANCE_EVIDENCE_INGESTION")),
    AUTHORING_TEST_GATE_READ(Set.of(
            "TEST_EXECUTION", "TEST_SUITE_READ", "GOVERNANCE_EVIDENCE_INGESTION")),
    CORRECTNESS_WORKSPACE_READ(Set.of(
            "CORRECTNESS_READ", "TEST_SUITE_READ", "GOVERNANCE_EVIDENCE_INGESTION")),
    CORRECTNESS_INVENTORY_WRITE(Set.of("CORRECTNESS_WRITE")),
    CORRECTNESS_INVENTORY_FREEZE(Set.of("CORRECTNESS_REVIEW")),
    CORRECTNESS_INVENTORY_IMPACT(Set.of("CORRECTNESS_READ", "CORRECTNESS_WRITE")),
    CORRECTNESS_ORACLE_WRITE(Set.of("CORRECTNESS_WRITE")),
    CORRECTNESS_ORACLE_APPROVE(Set.of("CORRECTNESS_REVIEW")),
    CORRECTNESS_ASSERTION_WRITE(Set.of("CORRECTNESS_WRITE")),
    CORRECTNESS_ASSERTION_VALIDATE(Set.of("CORRECTNESS_WRITE")),
    CORRECTNESS_SCENARIO_WRITE(Set.of("CORRECTNESS_WRITE")),
    CORRECTNESS_SCENARIO_REVIEW_READY(Set.of("CORRECTNESS_WRITE")),
    CORRECTNESS_SCENARIO_APPROVE(Set.of("CORRECTNESS_REVIEW")),
    CORRECTNESS_FIXTURE_WRITE(Set.of("CORRECTNESS_WRITE")),
    CORRECTNESS_FIXTURE_REVIEW_READY(Set.of("CORRECTNESS_WRITE")),
    CORRECTNESS_FIXTURE_APPROVE(Set.of("CORRECTNESS_REVIEW")),
    CORRECTNESS_FIXTURE_ACTIVATE(Set.of("CORRECTNESS_REVIEW")),
    CORRECTNESS_FIXTURE_REVOKE(Set.of("CORRECTNESS_REVIEW")),
    CORRECTNESS_FIXTURE_MATERIAL_WRITE(Set.of("CORRECTNESS_FIXTURE_MATERIAL_WRITE")),
    CORRECTNESS_FIXTURE_MATERIAL_READ(Set.of("CORRECTNESS_FIXTURE_MATERIAL_READ")),
    CORRECTNESS_COMPILATION_PREVIEW(Set.of("TEST_SCENARIO_PUBLISH")),
    CORRECTNESS_PUBLICATION_WRITE(Set.of("TEST_SCENARIO_PUBLISH")),
    CORRECTNESS_PUBLICATION_READ(Set.of("TEST_SCENARIO_PUBLISH")),
    CORRECTNESS_PREFLIGHT(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    CORRECTNESS_RUN_EXECUTE(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    CORRECTNESS_EVIDENCE_READ(Set.of(
            "TEST_EXECUTION", "TEST_SUITE_READ", "GOVERNANCE_EVIDENCE_INGESTION")),
    CORRECTNESS_OUTCOME_PROPOSAL_WRITE(Set.of("CORRECTNESS_WRITE")),
    CORRECTNESS_OUTCOME_PROPOSAL_READ(Set.of(
            "CORRECTNESS_READ", "CORRECTNESS_WRITE", "GOVERNANCE_EVIDENCE_INGESTION")),
    CORRECTNESS_GOVERNANCE_FEEDBACK_WRITE(Set.of("GOVERNANCE_GATE_FEEDBACK")),
    CORRECTNESS_GOVERNANCE_FEEDBACK_READ(Set.of(
            "CORRECTNESS_READ", "GOVERNANCE_GATE_FEEDBACK",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    REFERENCE_CANDIDATE_READ(Set.of(
            "CORRECTNESS_READ", "BUSINESS_MIRROR_AUTHORING", "TEST_SUITE_READ")),
    REFERENCE_CANDIDATE_RESOLVE(Set.of(
            "CORRECTNESS_READ", "BUSINESS_MIRROR_AUTHORING", "TEST_SUITE_READ")),
    AUTHORING_LINK_RESOLVE(Set.of(
            "BUSINESS_MIRROR_AUTHORING", "CHANGE_SYNC")),
    BUSINESS_MIRROR_PACKAGE_READ(Set.of(
            "BUSINESS_MIRROR_AUTHORING", "GOVERNANCE_EVIDENCE_INGESTION", "CHANGE_SYNC")),
    BUSINESS_MIRROR_PACKAGE_WRITE(Set.of("BUSINESS_MIRROR_AUTHORING")),
    BUSINESS_MIRROR_PACKAGE_COMPILE(Set.of("BUSINESS_MIRROR_AUTHORING", "MIRROR_REHEARSAL")),
    BUSINESS_MIRROR_IMPACT_READ(Set.of(
            "BUSINESS_MIRROR_AUTHORING", "GOVERNANCE_EVIDENCE_INGESTION", "CHANGE_SYNC")),
    BUSINESS_MIRROR_IMPACT_REBUILD(Set.of("BUSINESS_MIRROR_MAINTENANCE")),
    BUSINESS_MIRROR_EVIDENCE_READ(Set.of(
            "BUSINESS_MIRROR_AUTHORING", "GOVERNANCE_EVIDENCE_INGESTION", "CHANGE_SYNC")),
    BUSINESS_MIRROR_EVIDENCE_REFRESH(Set.of("BUSINESS_MIRROR_MAINTENANCE")),
    BUSINESS_MIRROR_EVIDENCE_TASK_WRITE(Set.of("BUSINESS_MIRROR_AUTHORING")),
    BUSINESS_MIRROR_REGISTRY_EXPORT(Set.of(
            "GOVERNANCE_EVIDENCE_INGESTION", "CHANGE_SYNC")),
    BUSINESS_MIRROR_GOVERNANCE_FEEDBACK(Set.of("GOVERNANCE_GATE_FEEDBACK")),
    BUSINESS_MIRROR_GOVERNANCE_READ(Set.of(
            "GOVERNANCE_EVIDENCE_INGESTION", "GOVERNANCE_GATE_FEEDBACK", "CHANGE_SYNC")),
    BUSINESS_MIRROR_PROPOSAL_READ(Set.of(
            "BUSINESS_MIRROR_AUTHORING", "GOVERNANCE_EVIDENCE_INGESTION", "CHANGE_SYNC")),
    BUSINESS_MIRROR_PROPOSAL_WRITE(Set.of("BUSINESS_MIRROR_AUTHORING")),
    BUSINESS_MIRROR_PROPOSAL_SIMULATE(Set.of("MIRROR_REHEARSAL")),
    BUSINESS_MIRROR_PROPOSAL_EVIDENCE_READ(Set.of(
            "MIRROR_REHEARSAL", "GOVERNANCE_EVIDENCE_INGESTION")),
    BUSINESS_MIRROR_IMPLEMENTATION_BIND(Set.of("CAPABILITY_IMPLEMENTATION")),
    BUSINESS_MIRROR_IMPLEMENTATION_READ(Set.of(
            "CAPABILITY_IMPLEMENTATION", "CAPABILITY_CONFORMANCE",
            "GOVERNANCE_EVIDENCE_INGESTION")),
    BUSINESS_MIRROR_IMPLEMENTATION_CONFORM(Set.of("CAPABILITY_CONFORMANCE")),
    BUSINESS_MIRROR_IMPLEMENTATION_CONFORMANCE_READ(Set.of(
            "CAPABILITY_CONFORMANCE", "GOVERNANCE_EVIDENCE_INGESTION")),
    TEST_DURABLE_EXECUTION_CREATE(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_EXECUTION_READ(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_OWNER_CLAIM(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_WORKER_ACQUISITION(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_RECOVERY_CONTROL(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_RECOVERY_STEP(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_RECOVERY_SEQUENCE(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_PROJECTION_MAINTENANCE(Set.of("TEST_RUNTIME_MAINTENANCE")),
    TEST_DURABLE_WORKER_QUARANTINE_MAINTENANCE(Set.of("TEST_RUNTIME_MAINTENANCE")),
    TEST_DURABLE_REQUEST_INDEX_ROLLOUT(Set.of("TEST_RUNTIME_MAINTENANCE")),
    TEST_TARGET_READ(Set.of("TEST_EXECUTION", "TEST_FIXTURE_READ", "TEST_FIXTURE_WRITE",
            "TEST_SUITE_READ", "TEST_SUITE_WRITE")),
    TEST_FIXTURE_READ(Set.of("TEST_FIXTURE_READ")),
    TEST_FIXTURE_WRITE(Set.of("TEST_FIXTURE_WRITE", "TEST_REPLAY")),
    TEST_REPLAY_READ(Set.of("TEST_REPLAY")),
    TEST_REPLAY_WRITE(Set.of("TEST_REPLAY")),
    TEST_SUITE_EXECUTION(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_SUITE_STABILITY_JOB_SUBMIT(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_SUITE_STABILITY_JOB_READ(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_SUITE_STABILITY_JOB_CANCEL(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_SUITE_STABILITY_TREND_READ(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_SUITE_READ(Set.of("TEST_SUITE_READ")),
    TEST_SUITE_WRITE(Set.of("TEST_SUITE_WRITE")),
    TEST_SCENARIO_PUBLISH(Set.of("TEST_SCENARIO_PUBLISH"));

    private final Set<String> acceptedPurposes;

    IntegrationOperation(Set<String> acceptedPurposes) {
        this.acceptedPurposes = Set.copyOf(acceptedPurposes);
    }

    public boolean accepts(String purpose) {
        return acceptedPurposes.contains(purpose == null ? "" : purpose.trim().toUpperCase(Locale.ROOT));
    }

    public Set<String> acceptedPurposes() {
        return acceptedPurposes;
    }
}
