package com.leanowtech.bloge.gateway.integration;

import java.util.Locale;
import java.util.Set;

/** Central operation-to-purpose policy for the Tool Studio integration surface. */
public enum IntegrationOperation {
    DRAFT_EXPORT(Set.of("GOVERNANCE_EVIDENCE_INGESTION", "CHANGE_SYNC")),
    WORKBOOK_EXPORT(Set.of("GOVERNANCE_EVIDENCE_INGESTION", "WORKBOOK_SYNC")),
    RUN_EVIDENCE_READ(Set.of("GOVERNANCE_EVIDENCE_INGESTION")),
    SIDE_EFFECT_RECONCILIATION_READ(Set.of(
            "GOVERNANCE_EVIDENCE_INGESTION", "SIDE_EFFECT_RECONCILIATION")),
    SIDE_EFFECT_RECONCILIATION_EXECUTE(Set.of("SIDE_EFFECT_RECONCILIATION")),
    RECORDED_PAYLOAD_READ(Set.of("GOVERNANCE_EVIDENCE_INGESTION", "PAYLOAD_REPLAY")),
    RECORDED_REPLAY(Set.of("PAYLOAD_REPLAY")),
    PAYLOAD_RETENTION_READ(Set.of("GOVERNANCE_EVIDENCE_INGESTION", "PAYLOAD_RETENTION_ADMIN", "LEGAL_HOLD")),
    PAYLOAD_RETENTION_ADMIN(Set.of("PAYLOAD_RETENTION_ADMIN")),
    PAYLOAD_LEGAL_HOLD(Set.of("LEGAL_HOLD")),
    EVIDENCE_TRUST_PUBLISH(Set.of("EVIDENCE_TRUST_ADMIN")),
    GATE_RESULT_WRITE(Set.of("GOVERNANCE_GATE_FEEDBACK")),
    GATE_RESULT_READ(Set.of("GOVERNANCE_EVIDENCE_INGESTION", "GOVERNANCE_GATE_FEEDBACK")),
    CHANGE_SYNC(Set.of("CHANGE_SYNC")),
    TEST_EXECUTION(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_EXECUTION_CREATE(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_EXECUTION_READ(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_OWNER_CLAIM(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_WORKER_ACQUISITION(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_RECOVERY_CONTROL(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_DURABLE_PROJECTION_MAINTENANCE(Set.of("TEST_RUNTIME_MAINTENANCE")),
    TEST_DURABLE_WORKER_QUARANTINE_MAINTENANCE(Set.of("TEST_RUNTIME_MAINTENANCE")),
    TEST_DURABLE_REQUEST_INDEX_ROLLOUT(Set.of("TEST_RUNTIME_MAINTENANCE")),
    TEST_TARGET_READ(Set.of("TEST_EXECUTION", "TEST_FIXTURE_READ", "TEST_FIXTURE_WRITE",
            "TEST_SUITE_READ", "TEST_SUITE_WRITE")),
    TEST_FIXTURE_READ(Set.of("TEST_FIXTURE_READ")),
    TEST_FIXTURE_WRITE(Set.of("TEST_FIXTURE_WRITE", "TEST_REPLAY")),
    TEST_REPLAY_READ(Set.of("TEST_REPLAY")),
    TEST_REPLAY_WRITE(Set.of("TEST_REPLAY")),
    TEST_SUITE_EXECUTION(Set.of("TEST_EXECUTION", "TEST_REPLAY")),
    TEST_SUITE_READ(Set.of("TEST_SUITE_READ")),
    TEST_SUITE_WRITE(Set.of("TEST_SUITE_WRITE"));

    private final Set<String> acceptedPurposes;

    IntegrationOperation(Set<String> acceptedPurposes) {
        this.acceptedPurposes = Set.copyOf(acceptedPurposes);
    }

    public boolean accepts(String purpose) {
        return acceptedPurposes.contains(purpose == null ? "" : purpose.trim().toUpperCase(Locale.ROOT));
    }

    public Set<String> acceptedPurposes() {
        return acceptedPurposes;
    }
}
