package com.leanowtech.bloge.gateway.testing.protocol;

/** Stable, closed reason codes for rejecting a BLOGE test-control header. */
public enum TestControlProtocolReason {
    INVALID_INPUT,
    DUPLICATE_HEADER,
    NULL_HEADER_VALUE,
    EMPTY_HEADER,
    HEADER_NOT_ASCII,
    ENCODED_VALUE_TOO_LARGE,
    INVALID_BASE64URL,
    NON_CANONICAL_BASE64URL,
    DECODED_VALUE_TOO_LARGE,
    INVALID_UTF8,
    MALFORMED_JSON,
    JSON_ROOT_NOT_OBJECT,
    JSON_DUPLICATE_FIELD,
    JSON_UNKNOWN_FIELD,
    JSON_DEPTH_EXCEEDED,
    JSON_CONTAINER_TOO_LARGE,
    JSON_STRING_TOO_LONG,
    MISSING_REQUIRED_FIELD,
    INVALID_FIELD_TYPE,
    ASSET_REFERENCE_CARDINALITY,
    INVALID_REVISION,
    INVALID_FINGERPRINT,
    INVALID_TOKEN,
    INLINE_NOT_OBJECT
}
