package com.leanowtech.bloge.gateway.testing.persistence;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.leanowtech.bloge.gateway.testing.api.TestSecurityEvent;
import com.leanowtech.bloge.gateway.testing.api.TestSecurityEventRepository;
import jakarta.annotation.PostConstruct;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.List;
import java.util.Map;

/** Append-only test-control security-event repository in the independent test database. */
public final class DatabaseTestSecurityEventRepository implements TestSecurityEventRepository {

    private final JdbcTemplate jdbc;
    private final ObjectMapper objectMapper;

    public DatabaseTestSecurityEventRepository(JdbcTemplate jdbc, ObjectMapper objectMapper) {
        this.jdbc = jdbc;
        this.objectMapper = objectMapper;
    }

    @PostConstruct
    public void init() {
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS rg_test_security_events (
                    sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    correlation_id VARCHAR(160) NOT NULL,
                    tenant_id VARCHAR(255) NOT NULL,
                    environment_id VARCHAR(255) NOT NULL,
                    actor_id VARCHAR(255) NOT NULL,
                    event_type VARCHAR(96) NOT NULL,
                    outcome VARCHAR(32) NOT NULL,
                    reason_code VARCHAR(160) NOT NULL,
                    facts_json CLOB NOT NULL
                )
                """);
    }

    @Override
    public TestSecurityEvent append(TestSecurityEvent event) {
        if (event == null || event.occurredAt() == null) {
            throw new IllegalArgumentException("Security event and timestamp are required");
        }
        KeyHolder keys = new GeneratedKeyHolder();
        jdbc.update(connection -> {
            PreparedStatement statement = connection.prepareStatement("""
                    INSERT INTO rg_test_security_events (
                        occurred_at, correlation_id, tenant_id, environment_id, actor_id,
                        event_type, outcome, reason_code, facts_json
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """, Statement.RETURN_GENERATED_KEYS);
            statement.setTimestamp(1, Timestamp.from(event.occurredAt()));
            statement.setString(2, event.correlationId());
            statement.setString(3, event.tenantId());
            statement.setString(4, event.environmentId());
            statement.setString(5, event.actorId());
            statement.setString(6, event.eventType());
            statement.setString(7, event.outcome());
            statement.setString(8, event.reasonCode());
            statement.setString(9, write(event.facts()));
            return statement;
        }, keys);
        Number key = keys.getKey();
        if (key == null) {
            throw new IllegalStateException("Security-event insert did not return a sequence");
        }
        return event.withSequence(key.longValue());
    }

    @Override
    public List<TestSecurityEvent> recent(int limit) {
        return jdbc.query("""
                        SELECT sequence, occurred_at, correlation_id, tenant_id, environment_id,
                               actor_id, event_type, outcome, reason_code, facts_json
                        FROM rg_test_security_events ORDER BY sequence DESC LIMIT ?
                        """, (rs, row) -> new TestSecurityEvent(
                        rs.getLong("sequence"), rs.getTimestamp("occurred_at").toInstant(),
                        rs.getString("correlation_id"), rs.getString("tenant_id"),
                        rs.getString("environment_id"), rs.getString("actor_id"),
                        rs.getString("event_type"), rs.getString("outcome"),
                        rs.getString("reason_code"), read(rs.getString("facts_json"))),
                Math.max(1, Math.min(1000, limit)));
    }

    private String write(Map<String, Object> facts) {
        try {
            return objectMapper.writeValueAsString(facts);
        } catch (JsonProcessingException failure) {
            throw new IllegalStateException("Cannot serialize test security event", failure);
        }
    }

    private Map<String, Object> read(String value) {
        try {
            return objectMapper.readValue(value, new TypeReference<>() { });
        } catch (JsonProcessingException failure) {
            throw new IllegalStateException("Stored test security event is corrupt", failure);
        }
    }
}
