package com.leanowtech.bloge.gateway.testing.verification;

public enum ValidatorSecurityDiagnostic {
    REJECTION_VERIFIED,
    MISSING_RECEIPT,
    RECEIPT_SET_MISMATCH,
    UNEXPECTED_RECEIPT,
    VALIDATOR_DID_NOT_REJECT,
    RECEIPT_BINDING_MISMATCH,
    RECEIPT_TAMPERED,
    RECEIPT_NOT_AUTHORIZED,
    TENANT_SCOPE_MISMATCH,
    PURPOSE_MISMATCH,
    RECEIPT_AUTHORITY_UNAVAILABLE,
    STALE_GOLDEN
}
