package com.leanowtech.bloge.gateway.integration.mirror;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.leanowtech.bloge.gateway.testing.persistence.MirrorStatePayloadProtector;
import org.springframework.dao.DataAccessException;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.function.Supplier;

import static com.leanowtech.bloge.gateway.integration.mirror.MirrorSessionStateStoreException.Code.CAPACITY_EXCEEDED;
import static com.leanowtech.bloge.gateway.integration.mirror.MirrorSessionStateStoreException.Code.CORRUPT;
import static com.leanowtech.bloge.gateway.integration.mirror.MirrorSessionStateStoreException.Code.CREATE_CONFLICT;
import static com.leanowtech.bloge.gateway.integration.mirror.MirrorSessionStateStoreException.Code.GONE;
import static com.leanowtech.bloge.gateway.integration.mirror.MirrorSessionStateStoreException.Code.LEASE_BUSY;
import static com.leanowtech.bloge.gateway.integration.mirror.MirrorSessionStateStoreException.Code.LEASE_LOST;
import static com.leanowtech.bloge.gateway.integration.mirror.MirrorSessionStateStoreException.Code.NOT_FOUND;
import static com.leanowtech.bloge.gateway.integration.mirror.MirrorSessionStateStoreException.Code.SESSION_ID_CONFLICT;
import static com.leanowtech.bloge.gateway.integration.mirror.MirrorSessionStateStoreException.Code.STATE_CONFLICT;
import static com.leanowtech.bloge.gateway.integration.mirror.MirrorSessionStateStoreException.Code.UNAVAILABLE;

/**
 * JDBC encrypted data-plane implementation of {@link MirrorSessionStateStore}.
 *
 * <p>The supplied JDBC template and transaction manager must belong to the dedicated mirror-state
 * data source, not the Resource Gateway control database. The table stores only an AES-GCM
 * envelope plus payload-free descriptor, fencing, lifecycle, and audit metadata. Every mutable
 * operation locks one exact full-scope row and uses the same local transaction for head metadata,
 * ciphertext replacement or erasure, and success audit.</p>
 */
public final class DatabaseMirrorSessionStateStore
        implements MirrorSessionStateStore {
    private static final long RETRY_AFTER_UNAVAILABLE_SECONDS = 5;
    private static final long MAXIMUM_CAPACITY_RETRY_SECONDS = 300;
    private static final int MAXIMUM_EXPIRY_SWEEP_BATCH = 1_000;
    private static final int GLOBAL_CAPACITY_GUARD = 1;
    private static final String CREATE_STATE_TABLE = """
            CREATE TABLE IF NOT EXISTS mirror_session_state (
                tenant_id VARCHAR(256) NOT NULL,
                organization_id VARCHAR(256) NOT NULL,
                project_id VARCHAR(256) NOT NULL,
                environment_id VARCHAR(256) NOT NULL,
                region VARCHAR(256) NOT NULL,
                session_id VARCHAR(512) NOT NULL,
                create_request_id VARCHAR(256) NOT NULL,
                create_fingerprint VARCHAR(71) NOT NULL,
                descriptor_json CLOB NOT NULL,
                descriptor_fingerprint VARCHAR(71) NOT NULL,
                status VARCHAR(16) NOT NULL,
                state_revision BIGINT NOT NULL,
                world_fingerprint VARCHAR(71) NOT NULL,
                state_fingerprint VARCHAR(71) NOT NULL,
                payload_fingerprint VARCHAR(71),
                payload_envelope CLOB,
                payload_bytes BIGINT NOT NULL,
                lease_owner VARCHAR(256),
                lease_fence BIGINT NOT NULL,
                lease_expires_at VARCHAR(64),
                expires_at VARCHAR(64) NOT NULL,
                created_at VARCHAR(64) NOT NULL,
                updated_at VARCHAR(64) NOT NULL,
                destroyed_at VARCHAR(64),
                PRIMARY KEY (
                    tenant_id, organization_id, project_id,
                    environment_id, region, session_id
                ),
                UNIQUE (
                    tenant_id, organization_id, project_id,
                    environment_id, region, create_request_id
                )
            )
            """;
    private static final String CREATE_AUDIT_TABLE = """
            CREATE TABLE IF NOT EXISTS mirror_session_operation_audit (
                audit_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tenant_id VARCHAR(256) NOT NULL,
                organization_id VARCHAR(256) NOT NULL,
                project_id VARCHAR(256) NOT NULL,
                environment_id VARCHAR(256) NOT NULL,
                region VARCHAR(256) NOT NULL,
                session_id VARCHAR(512) NOT NULL,
                observed_at VARCHAR(64) NOT NULL,
                operation VARCHAR(16) NOT NULL,
                outcome VARCHAR(16) NOT NULL,
                reason_code VARCHAR(192) NOT NULL,
                state_revision BIGINT NOT NULL,
                state_fingerprint VARCHAR(71) NOT NULL
            )
            """;
    private static final String CREATE_CAPACITY_GUARD_TABLE = """
            CREATE TABLE IF NOT EXISTS mirror_session_capacity_guard (
                guard_id INTEGER PRIMARY KEY
            )
            """;
    private static final String CREATE_CAPACITY_INDEX = """
            CREATE INDEX IF NOT EXISTS mirror_session_capacity_idx
            ON mirror_session_state (
                status, expires_at, payload_bytes
            )
            """;
    private static final String CREATE_SCOPE_CAPACITY_INDEX = """
            CREATE INDEX IF NOT EXISTS mirror_session_scope_capacity_idx
            ON mirror_session_state (
                tenant_id, organization_id, project_id,
                environment_id, region,
                status, expires_at, payload_bytes
            )
            """;
    private static final String SCOPE =
            "tenant_id = ? AND organization_id = ? AND project_id = ? "
                    + "AND environment_id = ? AND region = ?";
    private static final String SELECT_BY_SESSION = """
            SELECT descriptor_json, descriptor_fingerprint, status,
                   state_revision, world_fingerprint,
                   state_fingerprint, payload_fingerprint, payload_envelope,
                   payload_bytes, lease_owner, lease_fence, lease_expires_at,
                   expires_at, created_at, updated_at, destroyed_at,
                   create_request_id, create_fingerprint
              FROM mirror_session_state
             WHERE %s AND session_id = ?
            """.formatted(SCOPE);
    private static final String SELECT_BY_SESSION_FOR_UPDATE =
            SELECT_BY_SESSION + " FOR UPDATE";
    private static final String SELECT_BY_REQUEST = """
            SELECT descriptor_json, descriptor_fingerprint, status,
                   state_revision, world_fingerprint,
                   state_fingerprint, payload_fingerprint, payload_envelope,
                   payload_bytes, lease_owner, lease_fence, lease_expires_at,
                   expires_at, created_at, updated_at, destroyed_at,
                   create_request_id, create_fingerprint
              FROM mirror_session_state
             WHERE %s AND create_request_id = ?
            """.formatted(SCOPE);

    private final JdbcTemplate jdbc;
    private final ObjectMapper mapper;
    private final MirrorStatePayloadProtector protector;
    private final TransactionTemplate transaction;
    private final Supplier<Instant> coordinationClock;
    private final MirrorSessionCapacityPolicy capacityPolicy;
    private final MirrorSessionCapacityTelemetry capacityTelemetry;

    /**
     * Creates a durable encrypted store using the database clock.
     *
     * @param stateJdbc dedicated mirror-state JDBC boundary
     * @param mapper canonical protocol mapper
     * @param protector configured AES-256-GCM key ring
     * @param stateTransactionManager transaction manager for the same data source
     */
    public DatabaseMirrorSessionStateStore(
            JdbcTemplate stateJdbc,
            ObjectMapper mapper,
            MirrorStatePayloadProtector protector,
            PlatformTransactionManager stateTransactionManager) {
        this(stateJdbc, mapper, protector, stateTransactionManager,
                () -> databaseNow(stateJdbc));
    }

    /**
     * Creates a durable encrypted store with explicit capacity policy and database coordination
     * time.
     *
     * @param stateJdbc dedicated mirror-state JDBC boundary
     * @param mapper canonical protocol mapper
     * @param protector configured AES-256-GCM key ring
     * @param stateTransactionManager transaction manager for the same data source
     * @param capacityPolicy hierarchical database-authoritative hard limits
     * @param capacityTelemetry fixed-cardinality capacity telemetry sink
     */
    public DatabaseMirrorSessionStateStore(
            JdbcTemplate stateJdbc,
            ObjectMapper mapper,
            MirrorStatePayloadProtector protector,
            PlatformTransactionManager stateTransactionManager,
            MirrorSessionCapacityPolicy capacityPolicy,
            MirrorSessionCapacityTelemetry capacityTelemetry) {
        this(stateJdbc, mapper, protector, stateTransactionManager,
                () -> databaseNow(stateJdbc),
                capacityPolicy, capacityTelemetry);
    }

    /**
     * Creates a store with an explicit coordination clock for deterministic tests.
     *
     * @param stateJdbc dedicated mirror-state JDBC boundary
     * @param mapper canonical protocol mapper
     * @param protector configured AES-256-GCM key ring
     * @param stateTransactionManager transaction manager for the same data source
     * @param coordinationClock authoritative coordination time
     */
    public DatabaseMirrorSessionStateStore(
            JdbcTemplate stateJdbc,
            ObjectMapper mapper,
            MirrorStatePayloadProtector protector,
            PlatformTransactionManager stateTransactionManager,
            Supplier<Instant> coordinationClock) {
        this(stateJdbc, mapper, protector, stateTransactionManager,
                coordinationClock, MirrorSessionCapacityPolicy.defaults(),
                MirrorSessionCapacityTelemetry.noop());
    }

    /**
     * Creates a store with explicit cross-replica capacity policy and telemetry.
     *
     * @param stateJdbc dedicated mirror-state JDBC boundary
     * @param mapper canonical protocol mapper
     * @param protector configured AES-256-GCM key ring
     * @param stateTransactionManager transaction manager for the same data source
     * @param coordinationClock authoritative coordination time
     * @param capacityPolicy hierarchical database-authoritative hard limits
     * @param capacityTelemetry fixed-cardinality capacity telemetry sink
     */
    public DatabaseMirrorSessionStateStore(
            JdbcTemplate stateJdbc,
            ObjectMapper mapper,
            MirrorStatePayloadProtector protector,
            PlatformTransactionManager stateTransactionManager,
            Supplier<Instant> coordinationClock,
            MirrorSessionCapacityPolicy capacityPolicy,
            MirrorSessionCapacityTelemetry capacityTelemetry) {
        this.jdbc = Objects.requireNonNull(stateJdbc, "stateJdbc");
        this.mapper = Objects.requireNonNull(mapper, "mapper");
        this.protector = Objects.requireNonNull(protector, "protector");
        this.transaction = new TransactionTemplate(Objects.requireNonNull(
                stateTransactionManager, "stateTransactionManager"));
        this.coordinationClock = Objects.requireNonNull(
                coordinationClock, "coordinationClock");
        this.capacityPolicy = Objects.requireNonNull(
                capacityPolicy, "capacityPolicy");
        this.capacityTelemetry = Objects.requireNonNull(
                capacityTelemetry, "capacityTelemetry");
        jdbc.execute(CREATE_STATE_TABLE);
        jdbc.execute(CREATE_AUDIT_TABLE);
        jdbc.execute(CREATE_CAPACITY_GUARD_TABLE);
        jdbc.execute(CREATE_CAPACITY_INDEX);
        jdbc.execute(CREATE_SCOPE_CAPACITY_INDEX);
        jdbc.update("""
                MERGE INTO mirror_session_capacity_guard (guard_id)
                KEY (guard_id) VALUES (?)
                """, GLOBAL_CAPACITY_GUARD);
        capacityTelemetry.observe(globalSnapshot(globalCapacity(now())));
    }

    @Override
    public CreateResult create(CreateCommand command) {
        Objects.requireNonNull(command, "command");
        Instant now = now();
        MirrorSessionProtocolIntegrity.verifyInitial(
                mapper, command.payload(), now);
        SessionStateSpace state = command.payload().state();
        byte[] plaintext = serializePayload(command.payload());
        String envelope = protector.protect(plaintext,
                associatedData(state.scope(), state.sessionId(),
                        state.stateRevision(), command.payload().fingerprint()));
        MirrorSessionDescriptor descriptor = descriptor(
                command.payload(), MirrorSessionDescriptor.Status.ACTIVE,
                now, now, null);
        try {
            CreateMutation mutation = transaction.execute(ignored -> {
                lockCapacity();
                Optional<Row> byRequest = queryOne(
                        SELECT_BY_REQUEST,
                        scopeArgs(state.scope(), command.requestId()));
                if (byRequest.isPresent()) {
                    Row row = byRequest.orElseThrow();
                    if (!command.requestFingerprint().equals(
                            row.createFingerprint())) {
                        throw terminal(CREATE_CONFLICT);
                    }
                    return CreateMutation.replayed(new CreateResult(
                            CreateDisposition.REPLAYED,
                            readDescriptor(row)));
                }
                if (queryOne(SELECT_BY_SESSION, scopeArgs(
                        state.scope(), state.sessionId())).isPresent()) {
                    throw terminal(SESSION_ID_CONFLICT);
                }
                CapacityUsage usage = capacityUsage(now, state.scope());
                requireCreateCapacity(usage, plaintext.length, now);
                jdbc.update("""
                                INSERT INTO mirror_session_state (
                                    tenant_id, organization_id, project_id,
                                    environment_id, region, session_id,
                                    create_request_id, create_fingerprint,
                                    descriptor_json, descriptor_fingerprint,
                                    status, state_revision, world_fingerprint,
                                    state_fingerprint, payload_fingerprint,
                                    payload_envelope, payload_bytes,
                                    lease_owner, lease_fence, lease_expires_at,
                                    expires_at, created_at, updated_at, destroyed_at
                                ) VALUES (
                                    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                                    NULL, 0, NULL, ?, ?, ?, NULL
                                )
                                """,
                        state.scope().tenantId(),
                        state.scope().organizationId(),
                        state.scope().projectId(),
                        state.scope().environmentId(),
                        state.scope().region(),
                        state.sessionId(),
                        command.requestId(),
                        command.requestFingerprint(),
                        json(descriptor),
                        descriptor.fingerprint(),
                        descriptor.status().name(),
                        descriptor.stateRevision(),
                        descriptor.worldFingerprint(),
                        descriptor.stateFingerprint(),
                        command.payload().fingerprint(),
                        envelope,
                        plaintext.length,
                        descriptor.expiresAt().toString(),
                        descriptor.createdAt().toString(),
                        descriptor.updatedAt().toString());
                appendAudit(state.scope(), state.sessionId(), now,
                        Operation.CREATE, "", descriptor);
                return CreateMutation.created(
                        new CreateResult(
                                CreateDisposition.CREATED, descriptor),
                        globalSnapshot(
                                usage.global().plus(plaintext.length)));
            });
            if (mutation == null) {
                throw retryable(UNAVAILABLE,
                        RETRY_AFTER_UNAVAILABLE_SECONDS);
            }
            if (mutation.capacity() != null) {
                capacityTelemetry.observe(mutation.capacity());
            }
            return mutation.result();
        } catch (DuplicateKeyException duplicate) {
            return replayCreate(command);
        } catch (MirrorSessionStateStoreException expected) {
            throw expected;
        } catch (DataAccessException failure) {
            throw retryable(UNAVAILABLE, RETRY_AFTER_UNAVAILABLE_SECONDS);
        }
    }

    @Override
    public Optional<MirrorSessionDescriptor> find(
            CapabilitySnapshot.Scope scope, String sessionId) {
        requireScope(scope);
        String id = required(sessionId, "sessionId");
        try {
            return transaction.execute(ignored -> {
                Optional<Row> found = rowForUpdate(scope, id);
                if (found.isEmpty()) {
                    return Optional.empty();
                }
                Row row = found.orElseThrow();
                Instant now = now();
                if (row.active() && !row.expiresAt().isAfter(now)) {
                    return Optional.of(expire(scope, id, row, now));
                }
                return Optional.of(readDescriptor(row));
            });
        } catch (MirrorSessionStateStoreException expected) {
            throw expected;
        } catch (DataAccessException failure) {
            throw retryable(UNAVAILABLE, RETRY_AFTER_UNAVAILABLE_SECONDS);
        }
    }

    @Override
    public ClaimedSession claim(ClaimCommand command) {
        Objects.requireNonNull(command, "command");
        try {
            ClaimAttempt attempt = transaction.execute(ignored -> {
                Row row = rowForUpdate(command.scope(), command.sessionId())
                        .orElseThrow(() -> terminal(NOT_FOUND));
                Instant now = now();
                if (row.active() && !row.expiresAt().isAfter(now)) {
                    expire(command.scope(), command.sessionId(), row, now);
                    return ClaimAttempt.expiredAttempt();
                }
                if (!row.active()) {
                    throw terminal(GONE);
                }
                if (row.leaseExpiresAt() != null
                        && row.leaseExpiresAt().isAfter(now)
                        && !command.ownerId().equals(row.leaseOwner())) {
                    throw retryable(LEASE_BUSY,
                            retryAfter(now, row.leaseExpiresAt()));
                }
                long fence = Math.addExact(row.leaseFence(), 1);
                Instant leaseExpiresAt =
                        now.plusSeconds(command.leaseDurationSeconds());
                int updated = jdbc.update("""
                                UPDATE mirror_session_state
                                   SET lease_owner = ?,
                                       lease_fence = ?,
                                       lease_expires_at = ?
                                 WHERE %s AND session_id = ?
                                   AND lease_fence = ?
                                """.formatted(SCOPE),
                        concatArgs(
                                new Object[]{
                                        command.ownerId(),
                                        fence,
                                        leaseExpiresAt.toString()
                                },
                                scopeArgs(command.scope(), command.sessionId(),
                                        row.leaseFence())));
                if (updated != 1) {
                    throw retryable(LEASE_LOST, 1);
                }
                MirrorSessionPayload payload = decrypt(
                        command.scope(), command.sessionId(), row);
                MirrorSessionDescriptor descriptor = readDescriptor(row);
                Lease lease = new Lease(command.scope(), command.sessionId(),
                        command.ownerId(), fence, leaseExpiresAt);
                return ClaimAttempt.claimed(
                        new ClaimedSession(lease, payload, descriptor));
            });
            if (attempt.expired()) {
                throw terminal(GONE);
            }
            return attempt.session();
        } catch (MirrorSessionStateStoreException expected) {
            throw expected;
        } catch (DataAccessException failure) {
            throw retryable(UNAVAILABLE, RETRY_AFTER_UNAVAILABLE_SECONDS);
        }
    }

    @Override
    public boolean release(Lease lease) {
        Objects.requireNonNull(lease, "lease");
        try {
            return Boolean.TRUE.equals(transaction.execute(ignored -> {
                Optional<Row> found = rowForUpdate(
                        lease.scope(), lease.sessionId());
                if (found.isEmpty()) {
                    return false;
                }
                Row row = found.orElseThrow();
                Instant now = now();
                if (row.active() && !row.expiresAt().isAfter(now)) {
                    expire(lease.scope(), lease.sessionId(), row, now);
                    return false;
                }
                if (!row.active()
                        || !lease.ownerId().equals(row.leaseOwner())
                        || lease.fence() != row.leaseFence()) {
                    return false;
                }
                int updated = jdbc.update("""
                                UPDATE mirror_session_state
                                   SET lease_owner = NULL,
                                       lease_expires_at = NULL
                                 WHERE %s AND session_id = ?
                                   AND status = 'ACTIVE'
                                   AND lease_owner = ?
                                   AND lease_fence = ?
                                """.formatted(SCOPE),
                        scopeArgs(lease.scope(), lease.sessionId(),
                                lease.ownerId(), lease.fence()));
                return updated == 1;
            }));
        } catch (MirrorSessionStateStoreException expected) {
            throw expected;
        } catch (DataAccessException failure) {
            throw retryable(UNAVAILABLE, RETRY_AFTER_UNAVAILABLE_SECONDS);
        }
    }

    @Override
    public CommitResult compareAndSet(CommitCommand command) {
        Objects.requireNonNull(command, "command");
        MirrorSessionProtocolIntegrity.verify(mapper, command.candidate());
        SessionStateSpace candidateState = command.candidate().state();
        requireCandidateLease(command.lease(), candidateState);
        byte[] plaintext = serializePayload(command.candidate());
        String envelope = protector.protect(plaintext,
                associatedData(candidateState.scope(), candidateState.sessionId(),
                        candidateState.stateRevision(),
                        command.candidate().fingerprint()));
        try {
            CommitAttempt attempt = transaction.execute(ignored -> {
                CapabilitySnapshot.Scope scope = command.lease().scope();
                String sessionId = command.lease().sessionId();
                lockCapacity();
                Row row = rowForUpdate(scope, sessionId)
                        .orElseThrow(() -> terminal(NOT_FOUND));
                Instant now = now();
                if (row.active() && !row.expiresAt().isAfter(now)) {
                    expire(scope, sessionId, row, now);
                    return CommitAttempt.expiredAttempt();
                }
                requireCommitFence(command, row, now);
                MirrorSessionDescriptor previous = readDescriptor(row);
                requireCandidateClosure(previous, candidateState);
                CapacityUsage usage = capacityUsage(now, scope);
                requireCommitCapacity(
                        usage, row.payloadBytes(), plaintext.length, now);
                MirrorSessionDescriptor descriptor = descriptor(
                        command.candidate(),
                        MirrorSessionDescriptor.Status.ACTIVE,
                        previous.createdAt(), now, null);
                int updated = jdbc.update("""
                                UPDATE mirror_session_state
                                   SET descriptor_json = ?,
                                       descriptor_fingerprint = ?,
                                       state_revision = ?,
                                       world_fingerprint = ?,
                                       state_fingerprint = ?,
                                       payload_fingerprint = ?,
                                       payload_envelope = ?,
                                       payload_bytes = ?,
                                       updated_at = ?
                                 WHERE %s AND session_id = ?
                                   AND status = 'ACTIVE'
                                   AND state_fingerprint = ?
                                   AND lease_owner = ?
                                   AND lease_fence = ?
                                """.formatted(SCOPE),
                        concatArgs(
                                new Object[]{
                                        json(descriptor),
                                        descriptor.fingerprint(),
                                        descriptor.stateRevision(),
                                        descriptor.worldFingerprint(),
                                        descriptor.stateFingerprint(),
                                        command.candidate().fingerprint(),
                                        envelope,
                                        plaintext.length,
                                        now.toString()
                                },
                                scopeArgs(scope, sessionId,
                                        command.expectedStateFingerprint(),
                                        command.lease().ownerId(),
                                        command.lease().fence())));
                if (updated != 1) {
                    throw retryable(STATE_CONFLICT, 1);
                }
                appendAudit(scope, sessionId, now,
                        Operation.COMMIT, "", descriptor);
                return CommitAttempt.committed(
                        new CommitResult(descriptor),
                        globalSnapshot(usage.global().replace(
                                row.payloadBytes(), plaintext.length)));
            });
            if (attempt.expired()) {
                throw terminal(GONE);
            }
            capacityTelemetry.observe(attempt.capacity());
            return attempt.result();
        } catch (MirrorSessionStateStoreException expected) {
            throw expected;
        } catch (DataAccessException failure) {
            throw retryable(UNAVAILABLE, RETRY_AFTER_UNAVAILABLE_SECONDS);
        }
    }

    @Override
    public DestroyResult destroy(
            CapabilitySnapshot.Scope scope, String sessionId) {
        requireScope(scope);
        String id = required(sessionId, "sessionId");
        try {
            return transaction.execute(ignored -> {
                Row row = rowForUpdate(scope, id)
                        .orElseThrow(() -> terminal(NOT_FOUND));
                MirrorSessionDescriptor current = readDescriptor(row);
                if (current.status() == MirrorSessionDescriptor.Status.DESTROYED) {
                    return new DestroyResult(
                            DestroyDisposition.ALREADY_DESTROYED, current);
                }
                if (current.status() == MirrorSessionDescriptor.Status.EXPIRED) {
                    return new DestroyResult(
                            DestroyDisposition.EXPIRED, current);
                }
                Instant now = now();
                if (!row.expiresAt().isAfter(now)) {
                    return new DestroyResult(
                            DestroyDisposition.EXPIRED,
                            expire(scope, id, row, now));
                }
                MirrorSessionDescriptor destroyed = terminalize(
                        scope, id, row, now,
                        MirrorSessionDescriptor.Status.DESTROYED,
                        Operation.DESTROY);
                return new DestroyResult(
                        DestroyDisposition.DESTROYED, destroyed);
            });
        } catch (MirrorSessionStateStoreException expected) {
            throw expected;
        } catch (DataAccessException failure) {
            throw retryable(UNAVAILABLE, RETRY_AFTER_UNAVAILABLE_SECONDS);
        }
    }

    @Override
    public int expireDue(int limit) {
        if (limit < 1 || limit > MAXIMUM_EXPIRY_SWEEP_BATCH) {
            throw new IllegalArgumentException(
                    "mirror expiry sweep limit must be between 1 and "
                            + MAXIMUM_EXPIRY_SWEEP_BATCH);
        }
        try {
            ExpirySweep sweep = transaction.execute(ignored -> {
                lockCapacity();
                Instant now = now();
                List<SessionCoordinate> due = jdbc.query("""
                                SELECT tenant_id, organization_id, project_id,
                                       environment_id, region, session_id
                                  FROM mirror_session_state
                                 WHERE status = 'ACTIVE'
                                   AND expires_at <= ?
                                 ORDER BY expires_at,
                                          tenant_id, organization_id,
                                          project_id, environment_id,
                                          region, session_id
                                 LIMIT ?
                                """,
                        (rs, rowNum) -> new SessionCoordinate(
                                new CapabilitySnapshot.Scope(
                                        rs.getString("tenant_id"),
                                        rs.getString("organization_id"),
                                        rs.getString("project_id"),
                                        rs.getString("environment_id"),
                                        rs.getString("region")),
                                rs.getString("session_id")),
                        now.toString(), limit);
                int expired = 0;
                for (SessionCoordinate coordinate : due) {
                    Optional<Row> found = rowForUpdate(
                            coordinate.scope(), coordinate.sessionId());
                    if (found.isEmpty()) {
                        continue;
                    }
                    Row row = found.orElseThrow();
                    if (row.active()
                            && !row.expiresAt().isAfter(now)) {
                        expire(coordinate.scope(),
                                coordinate.sessionId(), row, now);
                        expired++;
                    }
                }
                return new ExpirySweep(
                        expired, globalSnapshot(globalCapacity(now)));
            });
            if (sweep == null) {
                throw retryable(UNAVAILABLE,
                        RETRY_AFTER_UNAVAILABLE_SECONDS);
            }
            capacityTelemetry.observe(sweep.capacity());
            return sweep.expired();
        } catch (MirrorSessionStateStoreException expected) {
            throw expected;
        } catch (DataAccessException failure) {
            throw retryable(UNAVAILABLE,
                    RETRY_AFTER_UNAVAILABLE_SECONDS);
        }
    }

    @Override
    public List<OperationAudit> recentAudit(
            CapabilitySnapshot.Scope scope,
            String sessionId,
            int limit) {
        requireScope(scope);
        String id = required(sessionId, "sessionId");
        int boundedLimit = Math.max(1, Math.min(500, limit));
        try {
            return jdbc.query("""
                            SELECT audit_sequence, observed_at, session_id,
                                   operation, outcome, reason_code,
                                   state_revision, state_fingerprint
                              FROM mirror_session_operation_audit
                             WHERE %s AND session_id = ?
                             ORDER BY audit_sequence DESC
                             LIMIT ?
                            """.formatted(SCOPE),
                    (rs, rowNum) -> new OperationAudit(
                            rs.getLong("audit_sequence"),
                            Instant.parse(rs.getString("observed_at")),
                            rs.getString("session_id"),
                            Operation.valueOf(rs.getString("operation")),
                            Outcome.valueOf(rs.getString("outcome")),
                            rs.getString("reason_code"),
                            rs.getLong("state_revision"),
                            rs.getString("state_fingerprint")),
                    scopeArgs(scope, id, boundedLimit));
        } catch (DataAccessException failure) {
            throw retryable(UNAVAILABLE, RETRY_AFTER_UNAVAILABLE_SECONDS);
        }
    }

    @Override
    public CapacitySnapshot capacity() {
        try {
            Instant observedAt = now();
            CapacitySnapshot snapshot = globalSnapshot(
                    globalCapacity(observedAt));
            capacityTelemetry.observe(snapshot);
            return snapshot;
        } catch (MirrorSessionStateStoreException expected) {
            throw expected;
        } catch (DataAccessException failure) {
            throw retryable(UNAVAILABLE,
                    RETRY_AFTER_UNAVAILABLE_SECONDS);
        }
    }

    @Override
    public boolean ready() {
        try {
            Integer one = jdbc.queryForObject("SELECT 1", Integer.class);
            return one != null && one == 1
                    && !protector.activeKeyId().isBlank();
        } catch (RuntimeException unavailable) {
            return false;
        }
    }

    private void lockCapacity() {
        Integer guard = jdbc.queryForObject("""
                SELECT guard_id
                  FROM mirror_session_capacity_guard
                 WHERE guard_id = ?
                 FOR UPDATE
                """, Integer.class, GLOBAL_CAPACITY_GUARD);
        if (guard == null || guard != GLOBAL_CAPACITY_GUARD) {
            throw terminal(CORRUPT);
        }
    }

    private CapacityUsage capacityUsage(
            Instant now, CapabilitySnapshot.Scope scope) {
        return new CapacityUsage(
                globalCapacity(now),
                scopeCapacity(now, scope));
    }

    private CapacityNumbers globalCapacity(Instant now) {
        return queryCapacity("""
                SELECT COALESCE(SUM(CASE
                           WHEN status = 'ACTIVE' AND expires_at > ?
                           THEN 1 ELSE 0 END), 0) AS active_sessions,
                       COALESCE(SUM(CASE
                           WHEN payload_bytes > 0
                           THEN payload_bytes ELSE 0 END), 0)
                           AS retained_payload_bytes,
                       COALESCE(SUM(CASE
                           WHEN status = 'ACTIVE' AND expires_at <= ?
                                AND payload_bytes > 0
                           THEN payload_bytes ELSE 0 END), 0)
                           AS expired_retained_payload_bytes,
                       MIN(CASE
                           WHEN status = 'ACTIVE' AND expires_at > ?
                           THEN expires_at ELSE NULL END) AS earliest_expiry
                  FROM mirror_session_state
                """, now.toString(), now.toString(), now.toString());
    }

    private CapacityNumbers scopeCapacity(
            Instant now, CapabilitySnapshot.Scope scope) {
        return queryCapacity("""
                SELECT COALESCE(SUM(CASE
                           WHEN status = 'ACTIVE' AND expires_at > ?
                           THEN 1 ELSE 0 END), 0) AS active_sessions,
                       COALESCE(SUM(CASE
                           WHEN payload_bytes > 0
                           THEN payload_bytes ELSE 0 END), 0)
                           AS retained_payload_bytes,
                       COALESCE(SUM(CASE
                           WHEN status = 'ACTIVE' AND expires_at <= ?
                                AND payload_bytes > 0
                           THEN payload_bytes ELSE 0 END), 0)
                           AS expired_retained_payload_bytes,
                       MIN(CASE
                           WHEN status = 'ACTIVE' AND expires_at > ?
                           THEN expires_at ELSE NULL END) AS earliest_expiry
                  FROM mirror_session_state
                 WHERE %s
                """.formatted(SCOPE),
                concatArgs(
                        new Object[]{
                                now.toString(),
                                now.toString(),
                                now.toString()
                        },
                        scopeArgs(scope)));
    }

    private CapacityNumbers queryCapacity(
            String sql, Object... arguments) {
        CapacityNumbers result = jdbc.queryForObject(
                sql,
                (rs, rowNum) -> new CapacityNumbers(
                        rs.getLong("active_sessions"),
                        rs.getLong("retained_payload_bytes"),
                        rs.getLong("expired_retained_payload_bytes"),
                        instant(rs.getString("earliest_expiry"))),
                arguments);
        return Objects.requireNonNull(
                result, "capacity query returned no aggregate");
    }

    private void requireCreateCapacity(
            CapacityUsage usage, long payloadBytes, Instant now) {
        CapacityNumbers global = usage.global().plus(payloadBytes);
        CapacityNumbers scope = usage.scope().plus(payloadBytes);
        if (global.activeSessions()
                > capacityPolicy.maximumActiveSessions()
                || global.retainedPayloadBytes()
                > capacityPolicy.maximumRetainedPayloadBytes()
                || scope.activeSessions()
                > capacityPolicy.maximumScopeActiveSessions()
                || scope.retainedPayloadBytes()
                > capacityPolicy.maximumScopeRetainedPayloadBytes()) {
            throw retryable(CAPACITY_EXCEEDED,
                    capacityRetryAfter(now, usage));
        }
    }

    private void requireCommitCapacity(
            CapacityUsage usage,
            long previousPayloadBytes,
            long candidatePayloadBytes,
            Instant now) {
        CapacityNumbers global = usage.global().replace(
                previousPayloadBytes, candidatePayloadBytes);
        CapacityNumbers scope = usage.scope().replace(
                previousPayloadBytes, candidatePayloadBytes);
        if (global.retainedPayloadBytes()
                > capacityPolicy.maximumRetainedPayloadBytes()
                || scope.retainedPayloadBytes()
                > capacityPolicy.maximumScopeRetainedPayloadBytes()) {
            throw retryable(CAPACITY_EXCEEDED,
                    capacityRetryAfter(now, usage));
        }
    }

    private long capacityRetryAfter(
            Instant now, CapacityUsage usage) {
        Instant earliest = earliest(
                usage.global().earliestExpiry(),
                usage.scope().earliestExpiry());
        if (earliest == null || !earliest.isAfter(now)) {
            return MAXIMUM_CAPACITY_RETRY_SECONDS;
        }
        return Math.min(
                MAXIMUM_CAPACITY_RETRY_SECONDS,
                retryAfter(now, earliest));
    }

    private CapacitySnapshot globalSnapshot(CapacityNumbers usage) {
        return new CapacitySnapshot(
                usage.activeSessions(),
                usage.retainedPayloadBytes(),
                usage.expiredRetainedPayloadBytes(),
                capacityPolicy.maximumActiveSessions(),
                capacityPolicy.maximumRetainedPayloadBytes());
    }

    private static Instant earliest(Instant first, Instant second) {
        if (first == null) {
            return second;
        }
        if (second == null) {
            return first;
        }
        return first.isBefore(second) ? first : second;
    }

    private CreateResult replayCreate(CreateCommand command) {
        CapabilitySnapshot.Scope scope = command.payload().state().scope();
        try {
            Optional<Row> byRequest = queryOne(
                    SELECT_BY_REQUEST,
                    scopeArgs(scope, command.requestId()));
            if (byRequest.isPresent()) {
                Row row = byRequest.orElseThrow();
                if (!command.requestFingerprint().equals(
                        row.createFingerprint())) {
                    throw terminal(CREATE_CONFLICT);
                }
                return new CreateResult(
                        CreateDisposition.REPLAYED, readDescriptor(row));
            }
            Optional<Row> bySession = queryOne(
                    SELECT_BY_SESSION,
                    scopeArgs(scope,
                            command.payload().state().sessionId()));
            if (bySession.isPresent()) {
                throw terminal(SESSION_ID_CONFLICT);
            }
            throw retryable(UNAVAILABLE, RETRY_AFTER_UNAVAILABLE_SECONDS);
        } catch (MirrorSessionStateStoreException expected) {
            throw expected;
        } catch (DataAccessException failure) {
            throw retryable(UNAVAILABLE, RETRY_AFTER_UNAVAILABLE_SECONDS);
        }
    }

    private MirrorSessionDescriptor expire(
            CapabilitySnapshot.Scope scope,
            String sessionId,
            Row row,
            Instant now) {
        return terminalize(scope, sessionId, row, now,
                MirrorSessionDescriptor.Status.EXPIRED, Operation.EXPIRE);
    }

    private MirrorSessionDescriptor terminalize(
            CapabilitySnapshot.Scope scope,
            String sessionId,
            Row row,
            Instant now,
            MirrorSessionDescriptor.Status status,
            Operation operation) {
        MirrorSessionDescriptor current = readDescriptor(row);
        MirrorSessionDescriptor terminal = MirrorSessionProtocolIntegrity.sealDescriptor(
                mapper, new MirrorSessionDescriptor(
                        MirrorSessionDescriptor.SCHEMA_VERSION,
                        current.sessionId(), current.scope(),
                        current.planFingerprint(), current.stateModelRef(),
                        current.writeEffectRefs(), current.stateRevision(),
                        status, current.worldFingerprint(),
                        current.stateFingerprint(), current.createdAt(), now,
                        current.expiresAt(), now, ""));
        int updated = jdbc.update("""
                        UPDATE mirror_session_state
                           SET descriptor_json = ?,
                               descriptor_fingerprint = ?,
                               status = ?,
                               payload_fingerprint = NULL,
                               payload_envelope = NULL,
                               payload_bytes = 0,
                               lease_owner = NULL,
                               lease_expires_at = NULL,
                               updated_at = ?,
                               destroyed_at = ?
                         WHERE %s AND session_id = ?
                           AND status = 'ACTIVE'
                        """.formatted(SCOPE),
                concatArgs(
                        new Object[]{
                                json(terminal),
                                terminal.fingerprint(),
                                status.name(),
                                now.toString(),
                                now.toString()
                        },
                        scopeArgs(scope, sessionId)));
        if (updated != 1) {
            throw retryable(STATE_CONFLICT, 1);
        }
        appendAudit(scope, sessionId, now, operation, "", terminal);
        return terminal;
    }

    private void requireCommitFence(
            CommitCommand command, Row row, Instant now) {
        if (!row.active()) {
            throw terminal(GONE);
        }
        if (!command.lease().ownerId().equals(row.leaseOwner())
                || command.lease().fence() != row.leaseFence()
                || row.leaseExpiresAt() == null
                || !row.leaseExpiresAt().isAfter(now)) {
            throw retryable(LEASE_LOST, 1);
        }
        if (!command.expectedStateFingerprint().equals(
                row.stateFingerprint())) {
            throw retryable(STATE_CONFLICT, 1);
        }
    }

    private static void requireCandidateLease(
            Lease lease, SessionStateSpace state) {
        if (!lease.scope().equals(state.scope())
                || !lease.sessionId().equals(state.sessionId())) {
            throw new IllegalArgumentException(
                    "candidate state does not match its lease");
        }
    }

    private static void requireCandidateClosure(
            MirrorSessionDescriptor previous,
            SessionStateSpace candidate) {
        if (candidate.stateRevision() != previous.stateRevision() + 1
                || !candidate.planFingerprint().equals(
                previous.planFingerprint())
                || !candidate.stateModelRef().equals(
                previous.stateModelRef())
                || !candidate.writeEffectRefs().equals(
                previous.writeEffectRefs())
                || !candidate.expiresAt().equals(previous.expiresAt())) {
            throw terminal(STATE_CONFLICT);
        }
    }

    private MirrorSessionPayload decrypt(
            CapabilitySnapshot.Scope scope, String sessionId, Row row) {
        if (row.payloadEnvelope() == null
                || row.payloadFingerprint() == null
                || row.payloadBytes() < 1
                || row.payloadBytes()
                > MirrorSessionProtocolIntegrity.MAXIMUM_PAYLOAD_BYTES) {
            throw terminal(CORRUPT);
        }
        try {
            byte[] plaintext = protector.unprotect(
                    row.payloadEnvelope(),
                    associatedData(scope, sessionId, row.stateRevision(),
                            row.payloadFingerprint()));
            if (plaintext.length != row.payloadBytes()) {
                throw terminal(CORRUPT);
            }
            MirrorSessionPayload payload =
                    mapper.readValue(plaintext, MirrorSessionPayload.class);
            MirrorSessionProtocolIntegrity.verify(mapper, payload);
            if (!payload.fingerprint().equals(row.payloadFingerprint())
                    || !payload.state().fingerprint().equals(
                    row.stateFingerprint())) {
                throw terminal(CORRUPT);
            }
            return payload;
        } catch (MirrorSessionStateStoreException expected) {
            throw expected;
        } catch (Exception invalid) {
            throw terminal(CORRUPT);
        }
    }

    private byte[] serializePayload(MirrorSessionPayload payload) {
        try {
            byte[] bytes = mapper.writeValueAsBytes(payload);
            if (bytes.length < 1 || bytes.length
                    > MirrorSessionProtocolIntegrity.MAXIMUM_PAYLOAD_BYTES) {
                throw retryable(
                        MirrorSessionStateStoreException.Code.CAPACITY_EXCEEDED, 1);
            }
            return bytes;
        } catch (MirrorSessionStateStoreException expected) {
            throw expected;
        } catch (JsonProcessingException invalid) {
            throw terminal(CORRUPT);
        }
    }

    private MirrorSessionDescriptor descriptor(
            MirrorSessionPayload payload,
            MirrorSessionDescriptor.Status status,
            Instant createdAt,
            Instant updatedAt,
            Instant destroyedAt) {
        SessionStateSpace state = payload.state();
        return MirrorSessionProtocolIntegrity.sealDescriptor(
                mapper, new MirrorSessionDescriptor(
                        MirrorSessionDescriptor.SCHEMA_VERSION,
                        state.sessionId(), state.scope(),
                        state.planFingerprint(), state.stateModelRef(),
                        state.writeEffectRefs(), state.stateRevision(), status,
                        state.worldFingerprint(), state.fingerprint(),
                        createdAt, updatedAt, state.expiresAt(),
                        destroyedAt, ""));
    }

    private MirrorSessionDescriptor readDescriptor(Row row) {
        try {
            MirrorSessionDescriptor descriptor = mapper.readValue(
                    row.descriptorJson(), MirrorSessionDescriptor.class);
            MirrorSessionProtocolIntegrity.verifyDescriptor(mapper, descriptor);
            if (!descriptor.fingerprint().equals(
                    row.descriptorFingerprint())
                    || !descriptor.status().name().equals(row.status())
                    || descriptor.stateRevision() != row.stateRevision()
                    || !descriptor.worldFingerprint().equals(
                    row.worldFingerprint())
                    || !descriptor.stateFingerprint().equals(
                    row.stateFingerprint())) {
                throw terminal(CORRUPT);
            }
            return descriptor;
        } catch (MirrorSessionStateStoreException expected) {
            throw expected;
        } catch (Exception invalid) {
            throw terminal(CORRUPT);
        }
    }

    private Optional<Row> rowForUpdate(
            CapabilitySnapshot.Scope scope, String sessionId) {
        return queryOne(SELECT_BY_SESSION_FOR_UPDATE,
                scopeArgs(scope, sessionId));
    }

    private Optional<Row> queryOne(String sql, Object[] arguments) {
        List<Row> rows = jdbc.query(sql, (rs, rowNum) -> new Row(
                rs.getString("descriptor_json"),
                rs.getString("status"),
                rs.getLong("state_revision"),
                rs.getString("world_fingerprint"),
                rs.getString("state_fingerprint"),
                rs.getString("payload_fingerprint"),
                rs.getString("payload_envelope"),
                rs.getLong("payload_bytes"),
                rs.getString("lease_owner"),
                rs.getLong("lease_fence"),
                instant(rs.getString("lease_expires_at")),
                Instant.parse(rs.getString("expires_at")),
                Instant.parse(rs.getString("created_at")),
                Instant.parse(rs.getString("updated_at")),
                instant(rs.getString("destroyed_at")),
                rs.getString("create_request_id"),
                rs.getString("create_fingerprint"),
                rs.getString("descriptor_fingerprint")),
                arguments);
        if (rows.size() > 1) {
            throw terminal(CORRUPT);
        }
        return rows.stream().findFirst();
    }

    private void appendAudit(
            CapabilitySnapshot.Scope scope,
            String sessionId,
            Instant now,
            Operation operation,
            String reasonCode,
            MirrorSessionDescriptor descriptor) {
        jdbc.update("""
                        INSERT INTO mirror_session_operation_audit (
                            tenant_id, organization_id, project_id,
                            environment_id, region, session_id,
                            observed_at, operation, outcome, reason_code,
                            state_revision, state_fingerprint
                        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                        """,
                scope.tenantId(), scope.organizationId(), scope.projectId(),
                scope.environmentId(), scope.region(), sessionId,
                now.toString(), operation.name(), Outcome.SUCCEEDED.name(),
                reasonCode == null ? "" : reasonCode,
                descriptor.stateRevision(), descriptor.stateFingerprint());
    }

    private String json(Object value) {
        try {
            return mapper.writeValueAsString(value);
        } catch (JsonProcessingException invalid) {
            throw terminal(CORRUPT);
        }
    }

    private Instant now() {
        try {
            return Objects.requireNonNull(
                    coordinationClock.get(), "coordinationClock returned null");
        } catch (MirrorSessionStateStoreException expected) {
            throw expected;
        } catch (RuntimeException unavailable) {
            throw retryable(UNAVAILABLE, RETRY_AFTER_UNAVAILABLE_SECONDS);
        }
    }

    private static Instant databaseNow(JdbcTemplate jdbc) {
        try {
            java.sql.Timestamp value = jdbc.queryForObject(
                    "SELECT CURRENT_TIMESTAMP", java.sql.Timestamp.class);
            return Objects.requireNonNull(
                    value, "mirror state database clock returned null").toInstant();
        } catch (DataAccessException unavailable) {
            throw retryable(UNAVAILABLE, RETRY_AFTER_UNAVAILABLE_SECONDS);
        }
    }

    private static String associatedData(
            CapabilitySnapshot.Scope scope,
            String sessionId,
            long revision,
            String payloadFingerprint) {
        return String.join("\0",
                "resourceGateway.mirrorStatePayload.v1",
                scope.tenantId(),
                scope.organizationId(),
                scope.projectId(),
                scope.environmentId(),
                scope.region(),
                sessionId,
                Long.toString(revision),
                payloadFingerprint);
    }

    private static Object[] scopeArgs(
            CapabilitySnapshot.Scope scope, Object... trailing) {
        Object[] arguments = new Object[5 + trailing.length];
        arguments[0] = scope.tenantId();
        arguments[1] = scope.organizationId();
        arguments[2] = scope.projectId();
        arguments[3] = scope.environmentId();
        arguments[4] = scope.region();
        System.arraycopy(trailing, 0, arguments, 5, trailing.length);
        return arguments;
    }

    private static Object[] concatArgs(Object[] leading, Object[] trailing) {
        Object[] arguments = new Object[leading.length + trailing.length];
        System.arraycopy(leading, 0, arguments, 0, leading.length);
        System.arraycopy(trailing, 0, arguments, leading.length, trailing.length);
        return arguments;
    }

    private static void requireScope(CapabilitySnapshot.Scope scope) {
        Objects.requireNonNull(scope, "scope");
    }

    private static String required(String value, String field) {
        String normalized = value == null ? "" : value.trim();
        if (normalized.isBlank()) {
            throw new IllegalArgumentException(field + " must not be blank");
        }
        return normalized;
    }

    private static Instant instant(String value) {
        return value == null || value.isBlank() ? null : Instant.parse(value);
    }

    private static long retryAfter(Instant now, Instant expiresAt) {
        Duration duration = Duration.between(now, expiresAt);
        long seconds = duration.getSeconds();
        return Math.max(1, duration.getNano() == 0
                ? seconds : Math.addExact(seconds, 1));
    }

    private static MirrorSessionStateStoreException terminal(
            MirrorSessionStateStoreException.Code code) {
        return new MirrorSessionStateStoreException(code, 0);
    }

    private static MirrorSessionStateStoreException retryable(
            MirrorSessionStateStoreException.Code code, long retryAfterSeconds) {
        return new MirrorSessionStateStoreException(code, retryAfterSeconds);
    }

    private record CreateMutation(
            CreateResult result,
            CapacitySnapshot capacity
    ) {
        private CreateMutation {
            result = Objects.requireNonNull(result, "result");
        }

        private static CreateMutation created(
                CreateResult result, CapacitySnapshot capacity) {
            return new CreateMutation(
                    result, Objects.requireNonNull(capacity, "capacity"));
        }

        private static CreateMutation replayed(CreateResult result) {
            return new CreateMutation(result, null);
        }
    }

    private record ExpirySweep(
            int expired,
            CapacitySnapshot capacity
    ) {
        private ExpirySweep {
            if (expired < 0) {
                throw new IllegalArgumentException(
                        "expired session count must not be negative");
            }
            capacity = Objects.requireNonNull(capacity, "capacity");
        }
    }

    private record SessionCoordinate(
            CapabilitySnapshot.Scope scope,
            String sessionId
    ) {
        private SessionCoordinate {
            scope = Objects.requireNonNull(scope, "scope");
            sessionId = required(sessionId, "sessionId");
        }
    }

    private record ClaimAttempt(
            ClaimedSession session,
            boolean expired
    ) {
        private static ClaimAttempt claimed(ClaimedSession session) {
            return new ClaimAttempt(
                    Objects.requireNonNull(session, "session"), false);
        }

        private static ClaimAttempt expiredAttempt() {
            return new ClaimAttempt(null, true);
        }
    }

    private record CommitAttempt(
            CommitResult result,
            CapacitySnapshot capacity,
            boolean expired
    ) {
        private static CommitAttempt committed(
                CommitResult result, CapacitySnapshot capacity) {
            return new CommitAttempt(
                    Objects.requireNonNull(result, "result"),
                    Objects.requireNonNull(capacity, "capacity"),
                    false);
        }

        private static CommitAttempt expiredAttempt() {
            return new CommitAttempt(null, null, true);
        }
    }

    private record CapacityUsage(
            CapacityNumbers global,
            CapacityNumbers scope
    ) {
        private CapacityUsage {
            global = Objects.requireNonNull(global, "global");
            scope = Objects.requireNonNull(scope, "scope");
        }
    }

    private record CapacityNumbers(
            long activeSessions,
            long retainedPayloadBytes,
            long expiredRetainedPayloadBytes,
            Instant earliestExpiry
    ) {
        private CapacityNumbers {
            if (activeSessions < 0
                    || retainedPayloadBytes < 0
                    || expiredRetainedPayloadBytes < 0
                    || expiredRetainedPayloadBytes > retainedPayloadBytes) {
                throw terminal(CORRUPT);
            }
        }

        private CapacityNumbers plus(long payloadBytes) {
            if (payloadBytes < 1) {
                throw terminal(CORRUPT);
            }
            try {
                return new CapacityNumbers(
                        Math.addExact(activeSessions, 1),
                        Math.addExact(
                                retainedPayloadBytes, payloadBytes),
                        expiredRetainedPayloadBytes,
                        earliestExpiry);
            } catch (ArithmeticException overflow) {
                throw retryable(
                        CAPACITY_EXCEEDED,
                        MAXIMUM_CAPACITY_RETRY_SECONDS);
            }
        }

        private CapacityNumbers replace(
                long previousPayloadBytes, long candidatePayloadBytes) {
            if (previousPayloadBytes < 1
                    || previousPayloadBytes > retainedPayloadBytes
                    || candidatePayloadBytes < 1) {
                throw terminal(CORRUPT);
            }
            try {
                return new CapacityNumbers(
                        activeSessions,
                        Math.addExact(
                                Math.subtractExact(
                                        retainedPayloadBytes,
                                        previousPayloadBytes),
                                candidatePayloadBytes),
                        expiredRetainedPayloadBytes,
                        earliestExpiry);
            } catch (ArithmeticException overflow) {
                throw retryable(
                        CAPACITY_EXCEEDED,
                        MAXIMUM_CAPACITY_RETRY_SECONDS);
            }
        }
    }

    private record Row(
            String descriptorJson,
            String status,
            long stateRevision,
            String worldFingerprint,
            String stateFingerprint,
            String payloadFingerprint,
            String payloadEnvelope,
            long payloadBytes,
            String leaseOwner,
            long leaseFence,
            Instant leaseExpiresAt,
            Instant expiresAt,
            Instant createdAt,
            Instant updatedAt,
            Instant destroyedAt,
            String createRequestId,
            String createFingerprint,
            String descriptorFingerprint
    ) {
        private boolean active() {
            return MirrorSessionDescriptor.Status.ACTIVE.name().equals(status);
        }
    }
}
