package com.leanowtech.bloge.gateway.integration.mirror;

import jakarta.annotation.PostConstruct;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;

import java.sql.PreparedStatement;
import java.util.List;
import java.util.Objects;

/** JDBC append-only implementation of the payload-free Mirror operation audit boundary. */
public final class DatabaseMirrorOperationAuditRepository
        implements MirrorOperationAuditRepository {
    private final JdbcTemplate jdbc;

    /**
     * Creates the database-backed audit repository.
     *
     * @param jdbc transaction-aware application JDBC boundary
     */
    public DatabaseMirrorOperationAuditRepository(JdbcTemplate jdbc) {
        this.jdbc = Objects.requireNonNull(jdbc, "jdbc");
    }

    /** Creates the payload-free audit table and exact-scope retrieval index. */
    @PostConstruct
    void init() {
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS mirror_operation_audit (
                    sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    tenant_id VARCHAR(255) NOT NULL,
                    organization_id VARCHAR(255) NOT NULL,
                    project_id VARCHAR(255) NOT NULL,
                    environment_id VARCHAR(255) NOT NULL,
                    region VARCHAR(96) NOT NULL,
                    correlation_id VARCHAR(160) NOT NULL,
                    actor_type VARCHAR(64) NOT NULL,
                    actor_id VARCHAR(255) NOT NULL,
                    operation VARCHAR(64) NOT NULL,
                    outcome VARCHAR(32) NOT NULL,
                    reason VARCHAR(32) NOT NULL,
                    reason_code VARCHAR(160) NOT NULL,
                    request_id VARCHAR(512) NOT NULL,
                    plan_id VARCHAR(512) NOT NULL,
                    run_id VARCHAR(512) NOT NULL,
                    duration_millis BIGINT NOT NULL
                )
                """);
        jdbc.execute("""
                ALTER TABLE mirror_operation_audit
                ALTER COLUMN operation VARCHAR(64)
                """);
        jdbc.execute("""
                CREATE INDEX IF NOT EXISTS idx_mirror_operation_audit_scope_sequence
                ON mirror_operation_audit (
                    tenant_id, organization_id, project_id, environment_id, region, sequence
                )
                """);
    }

    @Override
    public MirrorOperationAuditEvent append(MirrorOperationAuditEvent event) {
        MirrorOperationAuditEvent required = Objects.requireNonNull(event, "event");
        if (required.sequence() != 0 || required.occurredAt() != null) {
            throw new IllegalArgumentException("Mirror operation audit append requires a new event");
        }
        KeyHolder keys = new GeneratedKeyHolder();
        jdbc.update(connection -> {
            PreparedStatement statement = connection.prepareStatement("""
                    INSERT INTO mirror_operation_audit (
                        tenant_id, organization_id, project_id, environment_id, region,
                        correlation_id, actor_type, actor_id, operation, outcome, reason,
                        reason_code, request_id, plan_id, run_id, duration_millis
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """, new String[]{"sequence"});
            statement.setString(1, required.tenantId());
            statement.setString(2, required.organizationId());
            statement.setString(3, required.projectId());
            statement.setString(4, required.environmentId());
            statement.setString(5, required.region());
            statement.setString(6, required.correlationId());
            statement.setString(7, required.actorType());
            statement.setString(8, required.actorId());
            statement.setString(9, required.operation().name());
            statement.setString(10, required.outcome().name());
            statement.setString(11, required.reason().name());
            statement.setString(12, required.reasonCode());
            statement.setString(13, required.requestId());
            statement.setString(14, required.planId());
            statement.setString(15, required.runId());
            statement.setLong(16, required.durationMillis());
            return statement;
        }, keys);
        Number key = keys.getKey();
        if (key == null) {
            throw new IllegalStateException("Mirror operation audit insert returned no sequence");
        }
        return findSequence(key.longValue());
    }

    @Override
    public List<MirrorOperationAuditEvent> recent(
            CapabilitySnapshot.Scope scope, int limit) {
        CapabilitySnapshot.Scope required = Objects.requireNonNull(scope, "scope");
        return jdbc.query("""
                        SELECT sequence, occurred_at, tenant_id, organization_id, project_id,
                               environment_id, region, correlation_id, actor_type, actor_id,
                               operation, outcome, reason, reason_code, request_id, plan_id,
                               run_id, duration_millis
                        FROM mirror_operation_audit
                        WHERE tenant_id = ? AND organization_id = ? AND project_id = ?
                          AND environment_id = ? AND region = ?
                        ORDER BY sequence DESC
                        LIMIT ?
                        """, this::map,
                required.tenantId(), required.organizationId(), required.projectId(),
                required.environmentId(), required.region(), boundedLimit(limit));
    }

    private MirrorOperationAuditEvent findSequence(long sequence) {
        return jdbc.queryForObject("""
                        SELECT sequence, occurred_at, tenant_id, organization_id, project_id,
                               environment_id, region, correlation_id, actor_type, actor_id,
                               operation, outcome, reason, reason_code, request_id, plan_id,
                               run_id, duration_millis
                        FROM mirror_operation_audit
                        WHERE sequence = ?
                        """, this::map, sequence);
    }

    private MirrorOperationAuditEvent map(java.sql.ResultSet result, int row)
            throws java.sql.SQLException {
        return new MirrorOperationAuditEvent(
                result.getLong("sequence"), result.getTimestamp("occurred_at").toInstant(),
                result.getString("tenant_id"), result.getString("organization_id"),
                result.getString("project_id"), result.getString("environment_id"),
                result.getString("region"), result.getString("correlation_id"),
                result.getString("actor_type"), result.getString("actor_id"),
                MirrorOperationAuditEvent.Operation.valueOf(result.getString("operation")),
                MirrorOperationAuditEvent.Outcome.valueOf(result.getString("outcome")),
                MirrorOperationAuditEvent.Reason.valueOf(result.getString("reason")),
                result.getString("reason_code"), result.getString("request_id"),
                result.getString("plan_id"), result.getString("run_id"),
                result.getLong("duration_millis"));
    }

    private static int boundedLimit(int limit) {
        return Math.max(1, Math.min(1000, limit));
    }
}
