package com.leanowtech.bloge.gateway.integration.mirror;

import jakarta.annotation.PostConstruct;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;

import java.sql.PreparedStatement;
import java.util.List;
import java.util.Objects;

/**
 * JDBC append-only Scenario batch lifecycle audit with database sequence and occurrence time.
 */
public final class DatabaseScenarioRehearsalBatchLifecycleAuditRepository
        implements ScenarioRehearsalBatchLifecycleAuditRepository {
    private final JdbcTemplate jdbc;

    /**
     * @param jdbc transaction-aware application JDBC boundary
     */
    public DatabaseScenarioRehearsalBatchLifecycleAuditRepository(
            JdbcTemplate jdbc) {
        this.jdbc = Objects.requireNonNull(jdbc, "jdbc");
    }

    /** Creates the payload-free lifecycle table and exact-scope retrieval index. */
    @PostConstruct
    void init() {
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS scenario_rehearsal_batch_lifecycle_audit (
                    sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    tenant_id VARCHAR(255) NOT NULL,
                    organization_id VARCHAR(255) NOT NULL,
                    project_id VARCHAR(255) NOT NULL,
                    environment_id VARCHAR(255) NOT NULL,
                    region VARCHAR(64) NOT NULL,
                    job_id VARCHAR(512) NOT NULL,
                    request_id VARCHAR(256) NOT NULL,
                    manifest_fingerprint VARCHAR(71) NOT NULL,
                    transition VARCHAR(32) NOT NULL,
                    job_status VARCHAR(32) NOT NULL,
                    item_index INTEGER NOT NULL,
                    item_status VARCHAR(32) NOT NULL,
                    attempt_count INTEGER NOT NULL,
                    lease_owner VARCHAR(512) NOT NULL,
                    lease_epoch BIGINT NOT NULL,
                    evidence_bundle_fingerprint VARCHAR(71) NOT NULL,
                    reason_code VARCHAR(255) NOT NULL
                )
                """);
        jdbc.execute("""
                CREATE INDEX IF NOT EXISTS idx_scenario_rehearsal_batch_lifecycle_scope_job
                ON scenario_rehearsal_batch_lifecycle_audit (
                    tenant_id, organization_id, project_id,
                    environment_id, region, job_id, sequence
                )
                """);
    }

    @Override
    public ScenarioRehearsalBatchLifecycleAuditEvent append(
            ScenarioRehearsalBatchLifecycleAuditEvent event) {
        ScenarioRehearsalBatchLifecycleAuditEvent required =
                Objects.requireNonNull(event, "event");
        if (required.sequence() != 0
                || required.occurredAt() != null) {
            throw new IllegalArgumentException(
                    "Scenario batch lifecycle append requires a new event");
        }
        CapabilitySnapshot.Scope scope = required.scope();
        KeyHolder keys = new GeneratedKeyHolder();
        jdbc.update(connection -> {
            PreparedStatement statement =
                    connection.prepareStatement("""
                            INSERT INTO scenario_rehearsal_batch_lifecycle_audit (
                                tenant_id, organization_id, project_id,
                                environment_id, region, job_id, request_id,
                                manifest_fingerprint, transition, job_status,
                                item_index, item_status, attempt_count,
                                lease_owner, lease_epoch,
                                evidence_bundle_fingerprint, reason_code
                            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                                      ?, ?, ?, ?, ?, ?)
                            """, new String[]{"sequence"});
            statement.setString(1, scope.tenantId());
            statement.setString(2, scope.organizationId());
            statement.setString(3, scope.projectId());
            statement.setString(4, scope.environmentId());
            statement.setString(5, scope.region());
            statement.setString(6, required.jobId());
            statement.setString(7, required.requestId());
            statement.setString(
                    8, required.manifestFingerprint());
            statement.setString(
                    9, required.transition().name());
            statement.setString(
                    10, required.jobStatus().name());
            statement.setInt(11, required.itemIndex());
            statement.setString(
                    12, required.itemStatus().name());
            statement.setInt(13, required.attemptCount());
            statement.setString(14, required.leaseOwner());
            statement.setLong(15, required.leaseEpoch());
            statement.setString(
                    16, required.evidenceBundleFingerprint());
            statement.setString(17, required.reasonCode());
            return statement;
        }, keys);
        Number key = keys.getKey();
        if (key == null) {
            throw new IllegalStateException(
                    "Scenario batch lifecycle audit insert returned no sequence");
        }
        return find(key.longValue());
    }

    @Override
    public List<ScenarioRehearsalBatchLifecycleAuditEvent> lifecycle(
            CapabilitySnapshot.Scope scope,
            String jobId,
            int limit) {
        CapabilitySnapshot.Scope required =
                Objects.requireNonNull(scope, "scope");
        String job = boundedJob(jobId);
        return jdbc.query("""
                        SELECT sequence, occurred_at, job_id, request_id,
                               manifest_fingerprint, transition, job_status,
                               item_index, item_status, attempt_count,
                               lease_owner, lease_epoch,
                               evidence_bundle_fingerprint, reason_code
                        FROM scenario_rehearsal_batch_lifecycle_audit
                        WHERE tenant_id = ? AND organization_id = ?
                          AND project_id = ? AND environment_id = ?
                          AND region = ? AND job_id = ?
                        ORDER BY sequence
                        LIMIT ?
                        """,
                (result, row) -> map(result, required),
                required.tenantId(),
                required.organizationId(),
                required.projectId(),
                required.environmentId(),
                required.region(),
                job,
                boundedLimit(limit));
    }

    private ScenarioRehearsalBatchLifecycleAuditEvent find(
            long sequence) {
        return jdbc.queryForObject("""
                        SELECT sequence, occurred_at, tenant_id,
                               organization_id, project_id, environment_id,
                               region, job_id, request_id,
                               manifest_fingerprint, transition, job_status,
                               item_index, item_status, attempt_count,
                               lease_owner, lease_epoch,
                               evidence_bundle_fingerprint, reason_code
                        FROM scenario_rehearsal_batch_lifecycle_audit
                        WHERE sequence = ?
                        """,
                (result, row) -> map(
                        result,
                        new CapabilitySnapshot.Scope(
                                result.getString("tenant_id"),
                                result.getString("organization_id"),
                                result.getString("project_id"),
                                result.getString("environment_id"),
                                result.getString("region"))),
                sequence);
    }

    private static ScenarioRehearsalBatchLifecycleAuditEvent map(
            java.sql.ResultSet result,
            CapabilitySnapshot.Scope scope)
            throws java.sql.SQLException {
        return new ScenarioRehearsalBatchLifecycleAuditEvent(
                result.getLong("sequence"),
                result.getObject(
                        "occurred_at",
                        java.time.OffsetDateTime.class).toInstant(),
                scope,
                result.getString("job_id"),
                result.getString("request_id"),
                result.getString("manifest_fingerprint"),
                ScenarioRehearsalBatchLifecycleAuditEvent.Transition
                        .valueOf(result.getString("transition")),
                ScenarioRehearsalBatchJob.Status.valueOf(
                        result.getString("job_status")),
                result.getInt("item_index"),
                ScenarioRehearsalBatchLifecycleAuditEvent.ItemStatus
                        .valueOf(result.getString("item_status")),
                result.getInt("attempt_count"),
                result.getString("lease_owner"),
                result.getLong("lease_epoch"),
                result.getString(
                        "evidence_bundle_fingerprint"),
                result.getString("reason_code"));
    }

    private static int boundedLimit(int limit) {
        if (limit < 1 || limit > 10_000) {
            throw new IllegalArgumentException(
                    "Scenario batch lifecycle limit must be between 1 and 10000");
        }
        return limit;
    }

    private static String boundedJob(String jobId) {
        String normalized =
                jobId == null ? "" : jobId.trim();
        if (normalized.isBlank()
                || normalized.length() > 512) {
            throw new IllegalArgumentException(
                    "jobId is blank or exceeds its bound");
        }
        return normalized;
    }
}
