package com.leanowtech.bloge.gateway.integration.mirror;

import jakarta.annotation.PostConstruct;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;

import java.sql.PreparedStatement;
import java.util.List;
import java.util.Objects;

/**
 * JDBC append-only Scenario lifecycle audit with database sequence and occurrence time.
 */
public final class DatabaseScenarioRehearsalLifecycleAuditRepository
        implements ScenarioRehearsalLifecycleAuditRepository {
    private final JdbcTemplate jdbc;

    /**
     * @param jdbc transaction-aware application JDBC boundary
     */
    public DatabaseScenarioRehearsalLifecycleAuditRepository(
            JdbcTemplate jdbc) {
        this.jdbc = Objects.requireNonNull(jdbc, "jdbc");
    }

    /** Creates the payload-free lifecycle table and exact-scope retrieval index. */
    @PostConstruct
    void init() {
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS scenario_rehearsal_lifecycle_audit (
                    sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    tenant_id VARCHAR(255) NOT NULL,
                    organization_id VARCHAR(255) NOT NULL,
                    project_id VARCHAR(255) NOT NULL,
                    environment_id VARCHAR(255) NOT NULL,
                    region VARCHAR(64) NOT NULL,
                    request_id VARCHAR(256) NOT NULL,
                    compiled_plan_id VARCHAR(512) NOT NULL,
                    compiled_plan_revision BIGINT NOT NULL,
                    compiled_plan_fingerprint VARCHAR(71) NOT NULL,
                    run_id VARCHAR(512) NOT NULL,
                    transition VARCHAR(32) NOT NULL,
                    lease_owner VARCHAR(512) NOT NULL,
                    lease_epoch BIGINT NOT NULL,
                    total_cases INTEGER NOT NULL,
                    case_index INTEGER NOT NULL,
                    next_case_index INTEGER NOT NULL,
                    result_fingerprint VARCHAR(71) NOT NULL,
                    evidence_bundle_fingerprint VARCHAR(71) NOT NULL,
                    reason_code VARCHAR(256) NOT NULL
                )
                """);
        jdbc.execute("""
                CREATE INDEX IF NOT EXISTS idx_scenario_rehearsal_lifecycle_scope_request
                ON scenario_rehearsal_lifecycle_audit (
                    tenant_id, organization_id, project_id,
                    environment_id, region, request_id, sequence
                )
                """);
    }

    @Override
    public ScenarioRehearsalLifecycleAuditEvent append(
            ScenarioRehearsalLifecycleAuditEvent event) {
        ScenarioRehearsalLifecycleAuditEvent required =
                Objects.requireNonNull(event, "event");
        if (required.sequence() != 0
                || required.occurredAt() != null) {
            throw new IllegalArgumentException(
                    "Scenario lifecycle append requires a new event");
        }
        CapabilitySnapshot.Scope scope = required.scope();
        MirrorArtifactRef plan = required.compiledPlanRef();
        KeyHolder keys = new GeneratedKeyHolder();
        jdbc.update(connection -> {
            PreparedStatement statement =
                    connection.prepareStatement("""
                            INSERT INTO scenario_rehearsal_lifecycle_audit (
                                tenant_id, organization_id, project_id,
                                environment_id, region, request_id,
                                compiled_plan_id, compiled_plan_revision,
                                compiled_plan_fingerprint, run_id, transition,
                                lease_owner, lease_epoch, total_cases,
                                case_index, next_case_index, result_fingerprint,
                                evidence_bundle_fingerprint, reason_code
                            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                                      ?, ?, ?, ?, ?, ?, ?, ?)
                            """, new String[]{"sequence"});
            statement.setString(1, scope.tenantId());
            statement.setString(2, scope.organizationId());
            statement.setString(3, scope.projectId());
            statement.setString(4, scope.environmentId());
            statement.setString(5, scope.region());
            statement.setString(6, required.requestId());
            statement.setString(7, plan.id());
            statement.setLong(8, plan.revision());
            statement.setString(9, plan.fingerprint());
            statement.setString(10, required.runId());
            statement.setString(
                    11, required.transition().name());
            statement.setString(12, required.leaseOwner());
            statement.setLong(13, required.leaseEpoch());
            statement.setInt(14, required.totalCases());
            statement.setInt(15, required.caseIndex());
            statement.setInt(16, required.nextCaseIndex());
            statement.setString(
                    17, required.resultFingerprint());
            statement.setString(
                    18, required.evidenceBundleFingerprint());
            statement.setString(19, required.reasonCode());
            return statement;
        }, keys);
        Number key = keys.getKey();
        if (key == null) {
            throw new IllegalStateException(
                    "Scenario lifecycle audit insert returned no sequence");
        }
        return find(key.longValue());
    }

    @Override
    public List<ScenarioRehearsalLifecycleAuditEvent> lifecycle(
            CapabilitySnapshot.Scope scope,
            String requestId,
            int limit) {
        CapabilitySnapshot.Scope required =
                Objects.requireNonNull(scope, "scope");
        String request = boundedRequest(requestId);
        return jdbc.query("""
                        SELECT sequence, occurred_at, request_id,
                               compiled_plan_id, compiled_plan_revision,
                               compiled_plan_fingerprint, run_id, transition,
                               lease_owner, lease_epoch, total_cases,
                               case_index, next_case_index, result_fingerprint,
                               evidence_bundle_fingerprint, reason_code
                        FROM scenario_rehearsal_lifecycle_audit
                        WHERE tenant_id = ? AND organization_id = ?
                          AND project_id = ? AND environment_id = ?
                          AND region = ? AND request_id = ?
                        ORDER BY sequence
                        LIMIT ?
                        """,
                (result, row) -> map(result, required),
                required.tenantId(),
                required.organizationId(),
                required.projectId(),
                required.environmentId(),
                required.region(),
                request,
                boundedLimit(limit));
    }

    private ScenarioRehearsalLifecycleAuditEvent find(
            long sequence) {
        return jdbc.queryForObject("""
                        SELECT sequence, occurred_at, tenant_id,
                               organization_id, project_id, environment_id,
                               region, request_id, compiled_plan_id,
                               compiled_plan_revision,
                               compiled_plan_fingerprint, run_id, transition,
                               lease_owner, lease_epoch, total_cases,
                               case_index, next_case_index, result_fingerprint,
                               evidence_bundle_fingerprint, reason_code
                        FROM scenario_rehearsal_lifecycle_audit
                        WHERE sequence = ?
                        """,
                (result, row) -> map(
                        result,
                        new CapabilitySnapshot.Scope(
                                result.getString("tenant_id"),
                                result.getString("organization_id"),
                                result.getString("project_id"),
                                result.getString("environment_id"),
                                result.getString("region"))),
                sequence);
    }

    private static ScenarioRehearsalLifecycleAuditEvent map(
            java.sql.ResultSet result,
            CapabilitySnapshot.Scope scope)
            throws java.sql.SQLException {
        return new ScenarioRehearsalLifecycleAuditEvent(
                result.getLong("sequence"),
                result.getObject(
                        "occurred_at",
                        java.time.OffsetDateTime.class).toInstant(),
                scope,
                result.getString("request_id"),
                new MirrorArtifactRef(
                        "COMPILED_REHEARSAL_PLAN",
                        result.getString("compiled_plan_id"),
                        result.getLong(
                                "compiled_plan_revision"),
                        result.getString(
                                "compiled_plan_fingerprint")),
                result.getString("run_id"),
                ScenarioRehearsalLifecycleAuditEvent.Transition
                        .valueOf(result.getString("transition")),
                result.getString("lease_owner"),
                result.getLong("lease_epoch"),
                result.getInt("total_cases"),
                result.getInt("case_index"),
                result.getInt("next_case_index"),
                result.getString("result_fingerprint"),
                result.getString(
                        "evidence_bundle_fingerprint"),
                result.getString("reason_code"));
    }

    private static int boundedLimit(int limit) {
        if (limit < 1 || limit > 10_000) {
            throw new IllegalArgumentException(
                    "Scenario lifecycle limit must be between 1 and 10000");
        }
        return limit;
    }

    private static String boundedRequest(String requestId) {
        String normalized =
                requestId == null ? "" : requestId.trim();
        if (normalized.isBlank()
                || normalized.length() > 256) {
            throw new IllegalArgumentException(
                    "requestId is blank or exceeds its bound");
        }
        return normalized;
    }
}
