package com.leanowtech.bloge.gateway.testing.api;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.leanowtech.bloge.gateway.integration.IntegrationProblem;
import com.leanowtech.bloge.gateway.integration.IntegrationProblemException;
import com.leanowtech.bloge.gateway.integration.IntegrationRequestContext;
import com.leanowtech.bloge.gateway.testing.domain.SemanticCoveragePolicy;
import com.leanowtech.bloge.gateway.testing.domain.TestSuite;
import com.leanowtech.bloge.gateway.testing.domain.TestSuiteProtocol;
import com.leanowtech.bloge.gateway.testing.domain.TestSuiteV2;
import com.leanowtech.bloge.gateway.testing.domain.TestSuiteV3;
import com.leanowtech.bloge.gateway.testing.domain.TestSuiteV4;
import com.leanowtech.bloge.gateway.testing.domain.TestSuiteV5;
import com.leanowtech.bloge.gateway.testing.evidence.ProtocolFingerprint;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.regex.Pattern;

/**
 * Materializes one reviewed pure-DSL mutation plan and exact business oracle as an immutable V5
 * suite.
 *
 * <p>The complete bounded mutant closure is regenerated by the server. The caller cannot submit
 * mutant source or select favorable coordinates. The oracle is an existing immutable v1, v2, or
 * v4 suite; every exact fixture must contain at least one business assertion. Schema-admission and
 * recursively nested mutation suites are rejected because neither provides an independent
 * executable correctness oracle.</p>
 */
public final class TestMutationSuiteMaterializationService {
    private static final Pattern FINGERPRINT = Pattern.compile("sha256:[a-f0-9]{64}");
    private static final Pattern SAFE_ID = Pattern.compile("[A-Za-z0-9][A-Za-z0-9._-]{0,254}");
    private static final Set<String> CLASSIFICATIONS = Set.of(
            "PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED");

    private final TestExecutionApiService executions;
    private final TestSuiteRegistryService suites;
    private final ObjectMapper objectMapper;

    /**
     * @param executions exact plan regeneration and fixture lookup boundary
     * @param suites immutable suite registry
     * @param objectMapper canonical fingerprint mapper
     */
    public TestMutationSuiteMaterializationService(
            TestExecutionApiService executions,
            TestSuiteRegistryService suites,
            ObjectMapper objectMapper) {
        this.executions = Objects.requireNonNull(executions, "executions");
        this.suites = Objects.requireNonNull(suites, "suites");
        this.objectMapper = Objects.requireNonNull(objectMapper, "objectMapper");
    }

    /**
     * Regenerates and freezes the current exact graph mutation plan.
     *
     * @param graphName registered baseline graph
     * @param request reviewed optimistic identities and exact oracle reference
     * @param identity verified suite-write identity
     * @return content-addressed immutable V5 suite reference
     */
    public TestMutationSuiteMaterializationResponse materializeGraph(
            String graphName,
            TestMutationSuiteMaterializationRequest request,
            IntegrationRequestContext identity) {
        requireRequest(request, identity);
        TestMutationCasePlan plan = executions.planGraphMutationCases(
                graphName, request.maxMutants(), identity);
        requireExpectedPlan(plan, request, identity);
        StoredTestSuite oracle = requireOracle(plan, request, identity);
        return materialize(plan, oracle, request, identity);
    }

    private TestMutationSuiteMaterializationResponse materialize(
            TestMutationCasePlan plan,
            StoredTestSuite oracle,
            TestMutationSuiteMaterializationRequest request,
            IntegrationRequestContext identity) {
        TestSuiteProtocol oracleSuite = oracle.suite();
        SemanticCoveragePolicy semanticCoverage = oracleSuite instanceof TestSuiteV2 v2
                ? v2.semanticCoveragePolicy()
                : oracleSuite instanceof TestSuiteV4 v4
                ? v4.semanticCoveragePolicy() : SemanticCoveragePolicy.empty();
        TestSuiteV5.MutationPolicy mutationPolicy = mutationPolicy(plan.policy());
        List<TestSuiteV5.PlanningGap> gaps = plan.gaps().stream()
                .map(TestMutationSuiteMaterializationService::planningGap).toList();
        List<TestSuiteV5.MutantRef> mutants = plan.mutants().stream()
                .map(TestMutationSuiteMaterializationService::mutantRef).toList();
        TestSuiteV5.OracleSuiteRef oracleRef = new TestSuiteV5.OracleSuiteRef(
                oracle.suiteId(), oracle.revision(), oracle.fingerprint(), oracleSuite.schemaVersion());
        boolean gapsAccepted = plan.status() == TestMutationCasePlan.Status.PARTIAL;
        Map<String, Object> metadata = Map.of(
                "source", "pure-dsl-mutation-plan",
                "evaluationMode", TestSuiteV5.EvaluationMode.PURE_DSL_MUTATION.name(),
                "mutationPlanStatus", plan.status().name(),
                "planningGapCount", gaps.size(),
                "planningGapsAccepted", gapsAccepted,
                "oracleSuiteFingerprint", oracle.fingerprint(),
                "oracleCaseCount", oracleSuite.cases().size(),
                "mutantCount", mutants.size(),
                "mutantCaseExecutions", oracleSuite.cases().size() * mutants.size());
        TestSuiteV5 draft = new TestSuiteV5("", request.suiteId(), 1,
                new TestSuite.Target(plan.target().kind(), plan.target().id(),
                        plan.target().fingerprint()), request.classification(), oracleSuite.cases(),
                oracleSuite.coveragePolicy(), semanticCoverage, oracleSuite.promotionPolicy(),
                TestSuiteV5.EvaluationMode.PURE_DSL_MUTATION, plan.sourceFormat(),
                plan.sourceFingerprint(), plan.graphArtifactFingerprint(), plan.planFingerprint(),
                mutationPolicy, TestSuiteV5.SourcePlanStatus.valueOf(plan.status().name()),
                gapsAccepted, gaps, mutants, oracleRef, request.scorePolicy(), metadata);
        long revision = contentRevision(draft);
        TestSuiteV5 suite = new TestSuiteV5("", draft.suiteId(), revision, draft.target(),
                draft.classification(), draft.cases(), draft.coveragePolicy(),
                draft.semanticCoveragePolicy(), draft.promotionPolicy(), draft.evaluationMode(),
                draft.sourceFormat(), draft.baselineSourceFingerprint(),
                draft.baselineGraphArtifactFingerprint(), draft.mutationPlanFingerprint(),
                draft.mutationPolicy(), draft.sourcePlanStatus(), draft.planningGapsAccepted(),
                draft.planningGaps(), draft.mutants(), draft.oracleSuiteRef(), draft.scorePolicy(),
                draft.metadata());
        StoredTestSuite stored = suites.registerMutationSuite(request.suiteId(),
                new TestSuiteRegistrationRequest("", suite), plan, oracle, identity);
        TestSuiteExecutionRequest.SuiteRef oracleApiRef = new TestSuiteExecutionRequest.SuiteRef(
                oracle.suiteId(), oracle.revision(), oracle.fingerprint());
        TestSuiteExecutionRequest.SuiteRef suiteRef = new TestSuiteExecutionRequest.SuiteRef(
                stored.suiteId(), stored.revision(), stored.fingerprint());
        List<String> mutantIds = plan.mutants().stream()
                .map(TestMutationCasePlan.PlannedMutant::mutantId).toList();
        List<String> caseIds = oracleSuite.cases().stream()
                .map(TestSuite.TestCase::caseId).toList();
        Map<String, Object> responseMaterial = new LinkedHashMap<>();
        responseMaterial.put("schemaVersion", TestMutationSuiteMaterializationResponse.SCHEMA_VERSION);
        responseMaterial.put("target", plan.target());
        responseMaterial.put("baselineSourceFingerprint", plan.sourceFingerprint());
        responseMaterial.put("baselineGraphArtifactFingerprint", plan.graphArtifactFingerprint());
        responseMaterial.put("mutationPlanFingerprint", plan.planFingerprint());
        responseMaterial.put("sourcePlanStatus", plan.status().name());
        responseMaterial.put("planningGapsAccepted", gapsAccepted);
        responseMaterial.put("mutationPolicy", mutationPolicy);
        responseMaterial.put("mutantIds", mutantIds);
        responseMaterial.put("oracleCaseIds", caseIds);
        responseMaterial.put("mutantCaseExecutions", mutantIds.size() * caseIds.size());
        responseMaterial.put("oracleSuiteRef", oracleApiRef);
        responseMaterial.put("suiteRef", suiteRef);
        return new TestMutationSuiteMaterializationResponse("",
                ProtocolFingerprint.of(objectMapper, responseMaterial), plan.target(),
                plan.sourceFingerprint(), plan.graphArtifactFingerprint(), plan.planFingerprint(),
                plan.status(), gapsAccepted, mutationPolicy, mutantIds, caseIds,
                mutantIds.size() * caseIds.size(), oracleApiRef, suiteRef);
    }

    private StoredTestSuite requireOracle(
            TestMutationCasePlan plan,
            TestMutationSuiteMaterializationRequest request,
            IntegrationRequestContext identity) {
        TestSuiteExecutionRequest.SuiteRef ref = request.oracleSuiteRef();
        StoredTestSuite oracle = suites.find(ref.suiteId(), ref.revision(), identity);
        if (!ref.fingerprint().equals(oracle.fingerprint())) {
            throw conflict(identity, "RG.TEST.MUTATION_ORACLE_FINGERPRINT_CONFLICT",
                    "The governed oracle differs from the exact caller-reviewed reference.", Map.of());
        }
        TestSuiteProtocol suite = oracle.suite();
        if (suite instanceof TestSuiteV3 || suite instanceof TestSuiteV5
                || !(suite instanceof TestSuite || suite instanceof TestSuiteV2
                || suite instanceof TestSuiteV4)) {
            throw badRequest(identity, "RG.TEST.MUTATION_ORACLE_SUITE_UNSUPPORTED",
                    "Mutation oracles must be executable v1, v2, or v4 business suites.",
                    Map.of("schemaVersion", suite.schemaVersion()));
        }
        if (!"GRAPH".equals(suite.target().kind())
                || !plan.target().id().equals(suite.target().id())
                || !plan.target().fingerprint().equals(suite.target().fingerprint())) {
            throw conflict(identity, "RG.TEST.MUTATION_ORACLE_TARGET_MISMATCH",
                    "The oracle suite targets a different baseline graph artifact.", Map.of());
        }
        if (suite.cases().size() > TestSuiteV5.MAX_CASES
                || (long) suite.cases().size() * plan.mutants().size()
                > TestSuiteV5.MAX_MUTANT_CASE_EXECUTIONS) {
            throw badRequest(identity, "RG.TEST.MUTATION_SUITE_WORK_LIMIT_EXCEEDED",
                    "The mutation execution matrix exceeds generation-one bounds.",
                    Map.of("caseCount", suite.cases().size(),
                            "mutantCount", plan.mutants().size(),
                            "maximumWorkUnits", TestSuiteV5.MAX_MUTANT_CASE_EXECUTIONS));
        }
        for (TestSuite.TestCase testCase : suite.cases()) {
            TestSuite.FixtureBundleRef fixtureRef = testCase.fixtureBundleRef();
            StoredFixtureBundle fixture = executions.findFixture(
                    fixtureRef.fixtureBundleId(), fixtureRef.revision(), identity);
            if (!fixtureRef.fingerprint().equals(fixture.fingerprint())
                    || !plan.target().fingerprint().equals(fixture.bundle().targetFingerprint())) {
                throw conflict(identity, "RG.TEST.MUTATION_ORACLE_FIXTURE_STALE",
                        "An oracle fixture differs from its exact baseline-bound reference.",
                        Map.of("caseId", testCase.caseId()));
            }
            if (fixture.bundle().assertions().isEmpty()) {
                throw badRequest(identity, "RG.TEST.MUTATION_ORACLE_ASSERTIONS_REQUIRED",
                        "Every mutation oracle case requires a governed business assertion.",
                        Map.of("caseId", testCase.caseId(),
                                "fixtureBundleId", fixture.fixtureBundleId()));
            }
        }
        return oracle;
    }

    private static void requireRequest(
            TestMutationSuiteMaterializationRequest request,
            IntegrationRequestContext identity) {
        TestSuiteExecutionRequest.SuiteRef oracle = request == null
                ? null : request.oracleSuiteRef();
        if (request == null
                || !TestMutationSuiteMaterializationRequest.SCHEMA_VERSION.equals(
                request.schemaVersion())
                || !SAFE_ID.matcher(request.suiteId()).matches()
                || !CLASSIFICATIONS.contains(request.classification())
                || !fingerprint(request.expectedTargetFingerprint())
                || !fingerprint(request.expectedSourceFingerprint())
                || !fingerprint(request.expectedGraphArtifactFingerprint())
                || !fingerprint(request.expectedPlanFingerprint())
                || request.maxMutants() < 1 || request.maxMutants() > TestSuiteV5.MAX_MUTANTS
                || oracle == null || !SAFE_ID.matcher(oracle.suiteId()).matches()
                || oracle.revision() <= 0 || !fingerprint(oracle.fingerprint())
                || request.scorePolicy() == null) {
            throw badRequest(identity, "RG.TEST.MUTATION_SUITE_REQUEST_INVALID",
                    "A versioned request with exact proof identities, bounded policy, and oracle suite is required.",
                    Map.of());
        }
    }

    private static void requireExpectedPlan(
            TestMutationCasePlan plan,
            TestMutationSuiteMaterializationRequest request,
            IntegrationRequestContext identity) {
        if (!plan.target().fingerprint().equals(request.expectedTargetFingerprint())
                || !plan.sourceFingerprint().equals(request.expectedSourceFingerprint())
                || !plan.graphArtifactFingerprint()
                .equals(request.expectedGraphArtifactFingerprint())
                || !plan.planFingerprint().equals(request.expectedPlanFingerprint())) {
            throw conflict(identity, "RG.TEST.MUTATION_PLAN_FINGERPRINT_CONFLICT",
                    "The current exact mutation plan differs from the caller-reviewed identities.",
                    Map.of("currentTargetFingerprint", plan.target().fingerprint(),
                            "currentSourceFingerprint", plan.sourceFingerprint(),
                            "currentGraphArtifactFingerprint", plan.graphArtifactFingerprint(),
                            "currentPlanFingerprint", plan.planFingerprint()));
        }
        if (plan.status() == TestMutationCasePlan.Status.UNAVAILABLE) {
            throw badRequest(identity, "RG.TEST.MUTATION_PLAN_UNAVAILABLE",
                    "An unavailable mutation plan has no reproducible mutant to materialize.", Map.of());
        }
        if (plan.status() == TestMutationCasePlan.Status.PARTIAL
                && !request.acceptPlanningGaps()) {
            throw badRequest(identity, "RG.TEST.MUTATION_PLAN_GAPS_NOT_ACCEPTED",
                    "A partial mutation plan requires explicit planning-gap acceptance.",
                    Map.of("gapCount", plan.gaps().size()));
        }
    }

    private long contentRevision(TestSuiteV5 draft) {
        String fingerprint = ProtocolFingerprint.of(objectMapper,
                Map.of("assetKind", "MUTATION_SUITE", "content", draft));
        return Math.max(1, Long.parseLong(fingerprint.substring(
                "sha256:".length(), "sha256:".length() + 15), 16));
    }

    private static TestSuiteV5.MutationPolicy mutationPolicy(
            TestMutationCasePlan.MutationPolicy source) {
        return new TestSuiteV5.MutationPolicy(source.plannerVersion(), source.maxMutants(),
                source.sourceFormat(), source.verificationMode(),
                source.externalOperatorMutation(), source.equivalentMutantDetection());
    }

    private static TestSuiteV5.PlanningGap planningGap(
            TestMutationCasePlan.PlanningGap source) {
        return new TestSuiteV5.PlanningGap(
                TestSuiteV5.PlanningGapCode.valueOf(source.code().name()),
                source.astPath(), source.mutationKind());
    }

    private static TestSuiteV5.MutantRef mutantRef(
            TestMutationCasePlan.PlannedMutant source) {
        return new TestSuiteV5.MutantRef(source.mutantId(),
                TestSuiteV5.MutationKind.valueOf(source.kind().name()), source.astPath(),
                source.sourceLine(), source.sourceColumn(), source.mutantSourceFingerprint(),
                source.mutantGraphArtifactFingerprint(), source.mutantTargetFingerprint(),
                TestSuiteV5.EquivalenceClassification.valueOf(
                        source.equivalenceClassification().name()));
    }

    private static boolean fingerprint(String value) {
        return value != null && FINGERPRINT.matcher(value).matches();
    }

    private static IntegrationProblemException badRequest(
            IntegrationRequestContext identity, String code, String detail,
            Map<String, Object> details) {
        return new IntegrationProblemException(IntegrationProblem.badRequest(
                code, detail, identity.correlationId(), details));
    }

    private static IntegrationProblemException conflict(
            IntegrationRequestContext identity, String code, String detail,
            Map<String, Object> details) {
        return new IntegrationProblemException(IntegrationProblem.conflict(
                code, detail, identity.correlationId(), details));
    }
}
