-- Private Default Fixture Set revisions generated by compound API Resource saves.
-- Material is retained as Fixture authority JSON; the outer Resource journal
-- remains the only command receipt and visibility fence.

CREATE TABLE IF NOT EXISTS rg_api_fixture_set_identities (
    tenant_id VARCHAR(128) NOT NULL,
    project_id VARCHAR(128) NOT NULL,
    environment_id VARCHAR(128) NOT NULL,
    fixture_set_id VARCHAR(128) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT rg_api_fixture_set_identities_pk PRIMARY KEY
        (tenant_id, project_id, environment_id, fixture_set_id)
);

CREATE TABLE IF NOT EXISTS rg_api_fixture_set_revisions (
    tenant_id VARCHAR(128) NOT NULL,
    project_id VARCHAR(128) NOT NULL,
    environment_id VARCHAR(128) NOT NULL,
    fixture_set_id VARCHAR(128) NOT NULL,
    revision INTEGER NOT NULL,
    state VARCHAR(16) NOT NULL,
    fingerprint VARCHAR(71) NOT NULL,
    status VARCHAR(32) NOT NULL,
    status_revision INTEGER NOT NULL,
    subject_kind VARCHAR(32) NOT NULL,
    subject_id VARCHAR(128) NOT NULL,
    subject_revision INTEGER NOT NULL,
    subject_fingerprint VARCHAR(71) NOT NULL,
    generated_json TEXT NOT NULL,
    command_id VARCHAR(128) NOT NULL,
    attempt_no INTEGER NOT NULL,
    attempt_token VARCHAR(128) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    committed_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT rg_api_fixture_set_revisions_pk PRIMARY KEY
        (tenant_id, project_id, environment_id, fixture_set_id, revision,
         command_id, attempt_no, attempt_token),
    CONSTRAINT rg_api_fixture_set_revisions_attempt_fk FOREIGN KEY
        (command_id, attempt_no, attempt_token)
        REFERENCES rg_authoring_command_attempts (command_id, attempt_no, attempt_token),
    CONSTRAINT rg_api_fixture_set_revisions_identity_fk FOREIGN KEY
        (tenant_id, project_id, environment_id, fixture_set_id)
        REFERENCES rg_api_fixture_set_identities
            (tenant_id, project_id, environment_id, fixture_set_id),
    CONSTRAINT rg_api_fixture_set_revisions_state_ck CHECK
        (state IN ('STAGED', 'COMMITTED')),
    CONSTRAINT rg_api_fixture_set_revisions_status_ck CHECK
        (status = 'PRIVATE_DRAFT'),
    CONSTRAINT rg_api_fixture_set_revisions_revision_ck CHECK
        (revision > 0 AND status_revision > 0 AND subject_revision > 0),
    CONSTRAINT rg_api_fixture_set_revisions_fingerprint_ck CHECK
        (CHAR_LENGTH(fingerprint) = 71 AND fingerprint LIKE 'sha256:%'
         AND CHAR_LENGTH(subject_fingerprint) = 71
         AND subject_fingerprint LIKE 'sha256:%')
);

ALTER TABLE rg_api_fixture_set_revisions
    ADD CONSTRAINT rg_api_fixture_set_revisions_committed_ref_uq UNIQUE
        (tenant_id, project_id, environment_id, fixture_set_id, revision,
         command_id, attempt_no, attempt_token, state);

CREATE TABLE IF NOT EXISTS rg_api_fixture_set_heads (
    tenant_id VARCHAR(128) NOT NULL,
    project_id VARCHAR(128) NOT NULL,
    environment_id VARCHAR(128) NOT NULL,
    fixture_set_id VARCHAR(128) NOT NULL,
    revision INTEGER NOT NULL,
    command_id VARCHAR(128) NOT NULL,
    attempt_no INTEGER NOT NULL,
    attempt_token VARCHAR(128) NOT NULL,
    revision_state VARCHAR(16) NOT NULL DEFAULT 'COMMITTED',
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT rg_api_fixture_set_heads_pk PRIMARY KEY
        (tenant_id, project_id, environment_id, fixture_set_id),
    CONSTRAINT rg_api_fixture_set_heads_state_ck CHECK
        (revision_state = 'COMMITTED'),
    CONSTRAINT rg_api_fixture_set_heads_revision_fk FOREIGN KEY
        (tenant_id, project_id, environment_id, fixture_set_id, revision,
         command_id, attempt_no, attempt_token, revision_state)
        REFERENCES rg_api_fixture_set_revisions
            (tenant_id, project_id, environment_id, fixture_set_id, revision,
             command_id, attempt_no, attempt_token, state)
);

CREATE INDEX IF NOT EXISTS rg_api_fixture_set_subject_idx
    ON rg_api_fixture_set_revisions
       (tenant_id, project_id, environment_id, subject_kind, subject_id,
        subject_revision, subject_fingerprint, state, fixture_set_id);

CREATE INDEX IF NOT EXISTS rg_api_fixture_set_attempt_idx
    ON rg_api_fixture_set_revisions (command_id, attempt_no, attempt_token, state);
